backoffice:
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:l5AHWvgGBHeDcDaFJiC33iY3ZXKBFZT9SPQmJV+YxirpiRiHhFwojtnkvfm7ayb9j4rGlx59w3PpsbUbAPkrxyFc6o4L4nyp,iv:SrIKQsDI7c9xQutmvWLyeICqVLVy5CgOvL7CmhxNuVI=,tag:h3v3SjhRCF/jVcrZ/2jk3w==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ei3DBaEST8npRG5EQ6G1heGRbEoH5tPwVFCVt9TmcouksS0=,iv:Cfb/7K0i4x70o/vv4I5j63eSrycEgpQp9ikTKf+5neA=,tag:0eUQWI7CcgqdomWv/iK1cA==,type:str]
shell_environment:
    GOOGLE_TOTP_KEY: ENC[AES256_GCM,data:rg7FzP1kQOMcbWEKQnjR8EFHhUGu3koLqw9d3cP4E+7xYXYLwblQ,iv:9XSB1tKRxB7n/y9Cr8DgP1rHucjd6zcxkCvr3lG4+0U=,tag:PGxxz4xUewuB6d/rZeKGWw==,type:str]
    #ENC[AES256_GCM,data:SAV8d6Q6zCz4mOpAgrfDEhRQ6IabHh8j2DejMnOuOoGokAUQ,iv:51MqkAgXmRg2a/WV4Y4p0KUIl62sAKArcGjx1BuOH+s=,tag:/0Cdf/1gZ7X66O+Q6vpK+w==,type:comment]
    _ANTHROPIC_API_KEY: ENC[AES256_GCM,data:++nFGCW/G7Ua/29vC/Nl8wbqg9JiWYf+n05gZH3eluoXPdOsQ3MfQTUoMh6srkJMNpGKJJNShHWXkQar66jC8GsRSzSiB+S5CmglugI1abaN6bwys5WgVFLkOwliMItNyAsVi6TcHokALYad,iv:/37aAJunxcvEWndNZfuSl50TCHgX3wK1gYFPlRh6xdU=,tag:9u+9ToPpXjeroQ0m2+mKXw==,type:str]
    LINEAR_API_KEY: ENC[AES256_GCM,data:XlDkGWqTuza7vUcYYphqgiLot5mGubvhrNv2p8ipg02X5xMKkmnqy/7Jzjs99omV,iv:7QswcQoX9N5vX2+6ZhYjN5A4qtEZaIBuvhSe+uwjA4A=,tag:Gwki9t4SzsAgdDJ3O/tWjw==,type:str]
    FIGMA_CLIENTID: ENC[AES256_GCM,data:8xMmBHN/y3mTB7Qr4D6BntCMvfkKWg==,iv:0itSG5nTfB1ZDP//tgHcJ6sk7zDCsB36lWG95F+hXns=,tag:iA/C0v00fOwWRj1Gy08G4A==,type:str]
    FIGMA_CLIENTSECRET: ENC[AES256_GCM,data:QPIwcoDGOJv131m+nJDmBXzxs30Nvsq5157r0zP1,iv:1Bie0UMERX/JI8MbjhxejgLO+VPT36VGmODz/U+JH1E=,tag:aKAJI0hG2EYFEKGT42S2Tw==,type:str]
    DBURL: ENC[AES256_GCM,data:Smg1lQDw4KJnGN4qUmpMfPXKyd4IQm1lvM3/WgyhY+L+eQ/Jjk9gb+5bnSaLQcq6MgQ5NBEpMQTEZkbZ,iv:0U9zoyj6mGJjKoe94Bm6LQDn5+pX1R7NhvUhLOYbUiI=,tag:wsEYbd8g+a3qLRb3rUvDDw==,type:str]
    DBPORT: ENC[AES256_GCM,data:Mr7irw==,iv:x7Xq51129doV1at+/E3ouMA9gFlD8hHqwOcoHCkxtoo=,tag:x7jN8joUNNK066V8J6kSww==,type:int]
    DBUSER: ENC[AES256_GCM,data:xlvPTTN84X8FU6AVokeofXH2H3xYmCawpuoVfM7XotI=,iv:Ls+MwS+ti8SYaNG1eEmhEDCuw3YD8sRZ29GaFJb2ifw=,tag:EUk8RxytAMyX9WDxetvkpQ==,type:str]
    DBNAME: ENC[AES256_GCM,data:IkvrTlQ=,iv:iJzQCYBvozw3yzcCdqd71lQG1oFM/xm0WdB3mj8mU0w=,tag:uVAPr6hbVcDdYfH5+vd+MQ==,type:str]
    RHIZOME_TOKEN: ENC[AES256_GCM,data:qjKdcY9hU7enNiT1DJkl5p3aFcRtmfg4xMfZoB0DX0MtA7voy0WEZ4qFP0mvCmI9cR0wGMw=,iv:WjVR98sdSxX6Z6FwAcmp72V43fxvw/hHxuBTtKnQmnM=,tag:JYF31ouGSZIoDHuzdkWRcg==,type:str]
services:
    tailscale:
        authkey: ENC[AES256_GCM,data:YacigCGmzoxtN7qdbL3KVKLoOHoUW1zJ51eTVZrzJMF1k++Hb1D3Igxx070/Dyxgw8ElaBI9SsSN3NtMxyiNPorestlAcff9shAyHUYjoSnGr9NakhFvuQ==,iv:c/qLF1GEncbaz9JzNTPSyoHtZpomilMhVLqPTEVZ+XI=,tag:68H18q8F6LBPEqFaia5oWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlamNGZWlsVUFXcktWK1hE
            Qk1MbGJXYnRYVUVLbys2L0FyamdPTkx3R0Y0CmFwMHBiTEpUY1IxTng1Sk1ZMzNq
            N3lCTyt0aytQR2RPcXl4WlR4NitLMTAKLS0tIDB2TUd1dERYbTRUT2l3WWd5Rm1y
            bFo3L2VhZ0Z3akF0NVZ2UGRHWVdaeFUKHDg6ZNEkufRAsy3Hq3kaGcL+q3cpoujk
            +m3jDXkvPBpXKZJsJZkuiCvAfJgIYjUllAQBmor81d+5eStqHaihyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TTlDSkdxQTZnTmF4blVN
            aEpyZTRDdTMzZlY3L3ZFVUNDQXVaTUoxbjBvCnNwc011QnZ6cGd3cFJCUFJTanU5
            Qk1NamhJK2xaeXVUaVhpRkMyTG05YlEKLS0tIHNTKyt1cFJIV1JHay9RbTZtZ1pz
            VEd2TktoSmxrcDZlTGRRMjR6RTFpcEUKeVV0Aad5Am1M8a5SoHgY2fRc7OQuR5pB
            cIJjvn4LEDfHqnlxVfVoRnr8813Jj0wvVJOn48ATerm+er9ZjZXIzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qhlwc6f4yp7fylpzgeupjydyhvp6snjgvl0j8p6geynww8jzhyvq0cvwu2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aGhVV2pMdnJRZ3l1WG13
            Y05Sb01pNXMwb1kxNzJMYlhTUTNlWDhXMVFvCkN1QjNhRCtRK0ZBbDVYR1dEbmIv
            ck9uczhxZnJ6VVNFZlJCelBydWZKRzgKLS0tIDFjbXNZQmQ2VDBOV1d2ZTRHZTMw
            RjViZStOQ2NveEtOQTUvaDl6VU1XRG8KlaLtL11cBZ2PaWvRj8AueffXCrOMPVF5
            j6Opvp1NIEaPshaENBCJHfkeNK1WMhl0Eaje1iWs7Y0gJD3pUl0RKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14tstqskklfdq4uclxvxeygh6xj40f6axfm82r8umzvvs0de2f5zqen9vrd
    lastmodified: "2026-08-10T20:42:46Z"
    mac: ENC[AES256_GCM,data:4sJsox/huqV0LLVTVWMKGFVgTzxcq7Jgo6N2745SPybjV7vo5H0MLavtcLHnusv4MeKn8pOpvQffP9fvqPc3M5dR/xWKZkhEiDDkrZQa7lkQ9daheQkaIsX1cuO5IeceTUIJZHolPxM78DD0H09ebu6EJcU5epY49U7v7PNTHNI=,iv:LsVt4FxIOoWprAiMktUxex6ZQXO2yNj+qRIDOAhlhqM=,tag:qjxYP0KFN24ixCHSZV2vyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
