backoffice:
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:l5AHWvgGBHeDcDaFJiC33iY3ZXKBFZT9SPQmJV+YxirpiRiHhFwojtnkvfm7ayb9j4rGlx59w3PpsbUbAPkrxyFc6o4L4nyp,iv:SrIKQsDI7c9xQutmvWLyeICqVLVy5CgOvL7CmhxNuVI=,tag:h3v3SjhRCF/jVcrZ/2jk3w==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ei3DBaEST8npRG5EQ6G1heGRbEoH5tPwVFCVt9TmcouksS0=,iv:Cfb/7K0i4x70o/vv4I5j63eSrycEgpQp9ikTKf+5neA=,tag:0eUQWI7CcgqdomWv/iK1cA==,type:str]
shell_environment:
    GOOGLE_TOTP_KEY: ENC[AES256_GCM,data:rg7FzP1kQOMcbWEKQnjR8EFHhUGu3koLqw9d3cP4E+7xYXYLwblQ,iv:9XSB1tKRxB7n/y9Cr8DgP1rHucjd6zcxkCvr3lG4+0U=,tag:PGxxz4xUewuB6d/rZeKGWw==,type:str]
    #ENC[AES256_GCM,data:SAV8d6Q6zCz4mOpAgrfDEhRQ6IabHh8j2DejMnOuOoGokAUQ,iv:51MqkAgXmRg2a/WV4Y4p0KUIl62sAKArcGjx1BuOH+s=,tag:/0Cdf/1gZ7X66O+Q6vpK+w==,type:comment]
    _ANTHROPIC_API_KEY: ENC[AES256_GCM,data:++nFGCW/G7Ua/29vC/Nl8wbqg9JiWYf+n05gZH3eluoXPdOsQ3MfQTUoMh6srkJMNpGKJJNShHWXkQar66jC8GsRSzSiB+S5CmglugI1abaN6bwys5WgVFLkOwliMItNyAsVi6TcHokALYad,iv:/37aAJunxcvEWndNZfuSl50TCHgX3wK1gYFPlRh6xdU=,tag:9u+9ToPpXjeroQ0m2+mKXw==,type:str]
    LINEAR_API_KEY: ENC[AES256_GCM,data:XlDkGWqTuza7vUcYYphqgiLot5mGubvhrNv2p8ipg02X5xMKkmnqy/7Jzjs99omV,iv:7QswcQoX9N5vX2+6ZhYjN5A4qtEZaIBuvhSe+uwjA4A=,tag:Gwki9t4SzsAgdDJ3O/tWjw==,type:str]
sops:
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlamNGZWlsVUFXcktWK1hE
            Qk1MbGJXYnRYVUVLbys2L0FyamdPTkx3R0Y0CmFwMHBiTEpUY1IxTng1Sk1ZMzNq
            N3lCTyt0aytQR2RPcXl4WlR4NitLMTAKLS0tIDB2TUd1dERYbTRUT2l3WWd5Rm1y
            bFo3L2VhZ0Z3akF0NVZ2UGRHWVdaeFUKHDg6ZNEkufRAsy3Hq3kaGcL+q3cpoujk
            +m3jDXkvPBpXKZJsJZkuiCvAfJgIYjUllAQBmor81d+5eStqHaihyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qhlwc6f4yp7fylpzgeupjydyhvp6snjgvl0j8p6geynww8jzhyvq0cvwu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TTlDSkdxQTZnTmF4blVN
            aEpyZTRDdTMzZlY3L3ZFVUNDQXVaTUoxbjBvCnNwc011QnZ6cGd3cFJCUFJTanU5
            Qk1NamhJK2xaeXVUaVhpRkMyTG05YlEKLS0tIHNTKyt1cFJIV1JHay9RbTZtZ1pz
            VEd2TktoSmxrcDZlTGRRMjR6RTFpcEUKeVV0Aad5Am1M8a5SoHgY2fRc7OQuR5pB
            cIJjvn4LEDfHqnlxVfVoRnr8813Jj0wvVJOn48ATerm+er9ZjZXIzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14tstqskklfdq4uclxvxeygh6xj40f6axfm82r8umzvvs0de2f5zqen9vrd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aGhVV2pMdnJRZ3l1WG13
            Y05Sb01pNXMwb1kxNzJMYlhTUTNlWDhXMVFvCkN1QjNhRCtRK0ZBbDVYR1dEbmIv
            ck9uczhxZnJ6VVNFZlJCelBydWZKRzgKLS0tIDFjbXNZQmQ2VDBOV1d2ZTRHZTMw
            RjViZStOQ2NveEtOQTUvaDl6VU1XRG8KlaLtL11cBZ2PaWvRj8AueffXCrOMPVF5
            j6Opvp1NIEaPshaENBCJHfkeNK1WMhl0Eaje1iWs7Y0gJD3pUl0RKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T08:49:13Z"
    mac: ENC[AES256_GCM,data:JKj55RrWCGlh9CXnzUBYcCtDf9lOZ0X9eK2EaeBw4l5AX9d3tAqUuEP/zL4U4b4nx98jhWDmCZvw67iStj0/+poMa8d/hcvQqmHMFuxIFiQeFOPJLqLsov+Fso8rk/XSkj2aFjRihg/UAnW7pqjRddXtNShVoKwXTmLhtr8VSOU=,iv:60RmmRzAOJ4E+fy1MnKtPUR75sYiY2fY/vM8Ml8XQXw=,tag:EuQAqBT4nWArmwCA1yBLnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
