# Aggregates per-window key layers contributed by app modules and the user's
# `base` layer, then wires the assembled result into kanata + a generated
# Hyprland Lua fragment that switches kanata layers on window focus change.
#
# App modules (firefox, ghostty, slack, zen-browser, ...) contribute their
# slice via `keyLayers.layers.<name>`. The layer schema is documented in
# lib/key-layers.nix; shared building blocks live in `self.lib.keyLayers.presets`.
#
# There used to be a third leg here: hyprkan, a Python daemon that watched
# Hyprland's IPC socket, matched window class against a JSON rule file, and
# forwarded layer switches to kanata over TCP. Hyprland's own Lua config
# (configType = "lua") already gets a window-focus callback with the class
# on it for free, so the daemon, its rule schema, and the JSON intermediary
# were redundant -- this module now emits the equivalent ~30-line Lua
# fragment directly. Pulled in from hypr/hyprland.lua via
# `pcall(require, "kanata-app-layers")`, same pattern as the optional
# user.lua override -- the file only exists when keyLayers.enable is set.
{ self, ... }: {
  home =
    {
      config,
      pkgs,
      lib,
      ...
    }:
    with lib;
    let
      cfg = config.keyLayers;
      inherit (self.lib.keyLayers) mkKeyLayers;
      kl = mkKeyLayers cfg.layers;

      port = config.services.kanata.keyboards.${cfg.kanataKeyboard}.port;

      # Rules are ordered specific-first with a `*` wildcard fallback tacked
      # on by mkKeyLayers (see lib/key-layers.nix); the Lua below implements
      # that fallback itself (layerFor's default return), so the literal "*"
      # entry is dropped rather than emitted as a rule that can never match a
      # real class string. Only literal `class` is ever set by any layer
      # contributor today, so that's all this generates.
      # ponytail: exact class match only, no title/regex matching -- add
      # `w.title` / string.find into the Lua below if a layer ever needs it.
      rules = filter (r: (r.class or null) != null && r.class != "*") kl.windowRules;
      ruleLines = concatMapStringsSep ",\n  " (r: ''{ class = "${r.class}", layer = "${r.layer}" }'') rules;
    in
    {
      options.keyLayers = {
        enable = mkEnableOption "per-window kanata layer switching (kanata config + Hyprland Lua)";

        layers = mkOption {
          type = types.attrsOf types.anything;
          default = { };
          description = ''
            Map of layer name to layer definition, merged from app modules and the
            user config. See lib/key-layers.nix for the layer schema. "base" is the
            wildcard fallback for unmatched windows.
          '';
        };

        extraAliases = mkOption {
          type = types.lines;
          default = "";
          description = ''
            Extra kanata aliases injected into the generated config (host-specific,
            e.g. the application launcher command).
          '';
        };

        kanataKeyboard = mkOption {
          type = types.str;
          default = "main";
          description = "Name of the services.kanata.keyboards entry to populate and read the TCP port from.";
        };
      };

      config = mkIf cfg.enable {
        assertions = [
          {
            assertion = cfg.layers ? base;
            message = "keyLayers.enable is set but no `base` layer is defined.";
          }
          {
            assertion = port != null;
            message = "keyLayers.enable requires services.kanata.keyboards.${cfg.kanataKeyboard}.port to be set.";
          }
        ];

        services.kanata.keyboards.${cfg.kanataKeyboard}.config = kl.kanataConfig cfg.extraAliases;

        xdg.configFile."hypr/kanata-app-layers.lua".text = ''
          -- Generated by modules/keylayers. Switches kanata's active layer to
          -- match the focused window's class. Kept open over a single `nc`
          -- pipe rather than one exec_cmd per switch (hl.exec_cmd is
          -- fire-and-forget with no stdin -- see modules/keylayers/default.nix).
          local rules = {
            ${ruleLines}
          }

          local port = ${toString port}
          local sock = nil
          local lastLayer = nil

          local function send(layer)
            if lastLayer == layer then
              return
            end
            if not sock then
              sock = io.popen("${lib.getExe pkgs.netcat} 127.0.0.1 " .. port, "w")
              if not sock then
                return
              end
            end
            local ok = sock:write('{"ChangeLayer":{"new":"' .. layer .. '"}}\n')
            if ok then
              sock:flush()
              lastLayer = layer
            else
              -- kanata restarted and closed the pipe; drop it and retry next event.
              sock:close()
              sock = nil
            end
          end

          local function layerFor(class)
            for _, rule in ipairs(rules) do
              if class == rule.class then
                return rule.layer
              end
            end
            return "base"
          end

          hl.on("window.active", function(w)
            if w and w.class then
              send(layerFor(w.class))
            end
          end)
        '';
      };
    };
}
