[package]
name = "axum-website"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = "1.0.95"
askama = "0.12.1"
askama-filters = "0.1.3"

bytes = "1.10.0"
http = "1.2.0"
once_cell = "1.20.2"
pulldown-cmark = "0.12.2"
rand = "0.9.0"
serde_json ={workspace = true}
time = "0.3.37"
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing-subscriber = "0.3.18"
uuid = { version = "1.13.1", features = ["v4"] }



axum = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
app-state = { workspace = true }
feature-immo24 = { path = "../feature-immo24" } # This is a local path, not from workspace
reqwest = { workspace = true, features = ["json"] }
tracing = "0.1.41"
