{ lib, math, color-lib }:

{ lib, math, color-lib }:

let
  # Import necessary functions from the provided libraries
  inherit (lib) elemAt removePrefix;
  inherit (lib.lists) genList imap0 map; # Added map
  inherit (math) arange; # Assuming math.nix provides arange
  inherit (color-lib)
    # Core manipulation functions
    setOkhslLightness
    setOkhslSaturation
    setOkhslHue
    getOkhslLightness
    mixColors;
  # Potentially useful, but maybe not needed for this specific approach:
  # getOkhslSaturation getOkhslHue adjustOkhslHue adjustOkhslLightness etc.

  # --- Theme Anchors ---
  # Define the darkest background and lightest foreground hex codes.
  # These anchor the entire grayscale ramp.
  bg = "#1b2429"; # Dark Blue-Gray
  fg = "#ECEFF1"; # Light Gray

  # --- Hue Offset ---
  # Define an offset for the accent hues (0.0 to 1.0, wraps around)
  hueOffset = 0.125; # Default: 0.0 (no offset)

  # --- Neutral Tone ---
  # A mid-tone used for subtle mixing to increase cohesion across colors.
  # Derived by mixing the background and foreground.
  neutral = mixColors bg fg 0.5; # Mix halfway between bg and fg

  # --- Grayscale Generation (base00-base07) ---
  # Generate 8 perceptually uniform lightness steps between bg and fg.
  l_bg = getOkhslLightness bg;
  l_fg = getOkhslLightness fg;
  numGrays = 8;

  # Generate target lightness values from l_bg to l_fg using arange
  lightnessStep = (l_fg - l_bg) / (numGrays - 1);
  # Use arange: start, end (exclusive), step. Add step to end to include l_fg.
  # This ensures exactly numGrays elements, starting at l_bg and ending at l_fg.
  grayLightnesses = arange l_bg (l_fg + lightnessStep) lightnessStep;

  # Create the grayscale palette:
  # Iterate through the generated lightness values using index-aware map.
  # For each step, calculate the corresponding color mix between bg and fg.
  # Set the target lightness on the mixed color.
  # Mix slightly with 'neutral' for overall theme harmony.
  baseColors = imap0 (n: lightness: # n = index (0-7), lightness = value from grayLightnesses
    let
      # Calculate mix proportion between bg and fg (0.0 for bg, 1.0 for fg)
      mixProportion = n * 1.0 / (numGrays - 1);
      interpolatedColor = mixColors bg fg mixProportion;

      # Mix with neutral for cohesion
      neutralMixRatio = 0.1;
      neutralMixedColor = mixColors interpolatedColor neutral neutralMixRatio;

      # Set the target lightness from the generated list
      finalColor = setOkhslLightness lightness neutralMixedColor;
    in
      finalColor
  ) grayLightnesses; # Iterate over the list generated by arange

  # Assign generated grays to base00-base07 following Base16 convention
  # (base00 = darkest, base07 = lightest)
  base00 = elemAt baseColors 0; # Darkest Background
  base01 = elemAt baseColors 1; # Lighter Background (UI)
  base02 = elemAt baseColors 2; # Selection Background
  base03 = elemAt baseColors 3; # Comments, Low-contrast Fg
  base04 = elemAt baseColors 4; # Default Foreground (secondary)
  base05 = elemAt baseColors 5; # Default Foreground (primary)
  base06 = elemAt baseColors 6; # Light Foreground (UI)
  base07 = elemAt baseColors 7; # Lightest Foreground

  # --- Accent Color Generation (base08-base0F) ---
  # Define target perceptual lightness and saturation for accents.
  # Adjust these for desired vibrancy and contrast.
  accentL = 0.75; # Target lightness (perceptual) - adjust as needed
  accentS = 1.0; # Target saturation (perceptual) - adjust as needed

  # Generate 8 evenly spaced hues in Okhsl (0.0 to 1.0 scale)
  numHues = 8;
  # Generates [0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875]
  baseAccentHues = arange 0.0 1.0 (1.0 / numHues);

  # Helper for float modulo 1.0 (wraps hue values)
  mod1 = x: x - builtins.floor x;

  # Apply the offset to the base hues
  offsetAccentHues = map (hue: mod1 (hue + hueOffset)) baseAccentHues;

  # Helper function to create an accent color.
  # Starts from the neutral base, sets the target L/S, applies the specific hue,
  # and mixes with the theme's neutral color for cohesion.
  createAccent = targetHue:
    let
      # Start with neutral, set target Lightness and Saturation
      baseAccent = setOkhslSaturation accentS neutral;
      # Apply the specific hue
      hueSetColor = setOkhslHue targetHue baseAccent;
      # Mix slightly with neutral for overall theme harmony (consistent mix ratio)
      mixRatio = 0.1;
      neutralMixedColor = mixColors hueSetColor neutral mixRatio;
    in
      setOkhslLightness accentL neutralMixedColor;

  # Generate the 8 accent colors using the offset hues
  # The perceived color (Red, Orange, etc.) will depend on the hueOffset.
  base08 = createAccent (elemAt offsetAccentHues 0); # Accent 1
  base09 = createAccent (elemAt offsetAccentHues 1); # Accent 2
  base0A = createAccent (elemAt offsetAccentHues 2); # Accent 3
  base0B = createAccent (elemAt offsetAccentHues 3); # Accent 4
  base0C = createAccent (elemAt offsetAccentHues 4); # Accent 5
  base0D = createAccent (elemAt offsetAccentHues 5); # Accent 6
  base0E = createAccent (elemAt offsetAccentHues 6); # Accent 7
  base0F = createAccent (elemAt offsetAccentHues 7); # Accent 8

  # --- Determine Theme Type (Optional Metadata) ---
  bgLightness = getOkhslLightness bg;
  themeType = if bgLightness < 0.5 then "dark" else "light";

in {
  #type = themeType;

  # Expose Generated Base16 Palette (removing '#' prefix)
  base00 = lib.removePrefix "#" base00; # theme.base00
  base01 = lib.removePrefix "#" base01; # theme.base01
  base02 = lib.removePrefix "#" base02; # theme.base02
  base03 = lib.removePrefix "#" base03; # theme.base03
  base04 = lib.removePrefix "#" base04; # theme.base04
  base05 = lib.removePrefix "#" base05; # theme.base05
  base06 = lib.removePrefix "#" base06; # theme.base06
  base07 = lib.removePrefix "#" base07; # theme.base07
  base08 = lib.removePrefix "#" base08; # theme.base08
  base09 = lib.removePrefix "#" base09; # theme.base09
  base0A = lib.removePrefix "#" base0A; # theme.base0A
  base0B = lib.removePrefix "#" base0B; # theme.base0B
  base0C = lib.removePrefix "#" base0C; # theme.base0C
  base0D = lib.removePrefix "#" base0D; # theme.base0D
  base0E = lib.removePrefix "#" base0E; # theme.base0E
  base0F = lib.removePrefix "#" base0F; # theme.base0F
}

