[package]
name = "axum-website"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
askama = "0.12.1"
askama-filters = "0.1.3"
axum = { version = "0.7.9", features = ["macros"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "sqlite"] }
time = "0.3.37"
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing-subscriber = "0.3.18"
uuid = { version = "1.13.1", features = ["v4"] }
