[package]
name = "axum-website"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
askama = "0.12.1"
askama-filters = "0.1.3"
aws-config = { version = "1.5.16", features = ["behavior-version-latest"] }
aws-sdk-textract = "1.59.0"
aws-smithy-runtime-api = "1.7.3"
aws-types = "1.3.5"
axum = { version = "0.7.9", features = ["macros", "multipart"] }
http = "1.2.0"
lazy_static = "1.5.0"
mime = "0.3.17"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "sqlite"] }
time = "0.3.37"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.13", features = ["compat"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.13.1", features = ["v4"] }
