hello: ENC[AES256_GCM,data:ISMnI1i6cFiTxTpv8BYPak6e16GJ93ZpI/09FKB07HLyLh6W/uaHQm+doSXzXQ==,iv:HKUThVA+o1r03pjtNza1YuG4KbpIq+a4hvNG6LQuB70=,tag:G+kwgOt6FaN5mkMrW1F2Wg==,type:str]
example_key: ENC[AES256_GCM,data:hVkTOKu0bKIqKEbcnA==,iv:YrzEw+jM8L8Oc7ZMlrNtQKAnhYEE/IXzcXahnVIosUc=,tag:56SLvMbOMlxmBeoEH/207Q==,type:str]
#ENC[AES256_GCM,data:PGM/OncrOckJ5CywWocr2Q==,iv:wKbG9swFnzlmluzBFXLRKoKh3scgu+oanFwNtQF980Q=,tag:2DCuR6UHoIsYTtHXARzPqg==,type:comment]
example_array:
    - ENC[AES256_GCM,data:Q+1fMfu1sVCPj7OV/wI=,iv:OrMW9qHIx1Tc/ql9SPUdTvNTfVtzJJer+D9w3r9vdN8=,tag:Nr7IdwRqRgwSQt6GvUN9Aw==,type:str]
    - ENC[AES256_GCM,data:23GSS4Xm4on2PXXjThU=,iv:mWVcFJl06XVIIbc/g5OOFMxkZgG/pxRNx7TiAD7U4WM=,tag:jajbvc7vAwMcaOiwhaWvbA==,type:str]
example_number: ENC[AES256_GCM,data:3UiyD0G10jA1ug==,iv:UZ66M8yh3uP6k6pEbtXVCZbkh+ohl1npYoVP4ZaGrRk=,tag:kQkvBGKpdDDjYl0A6orvmg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:YLHtEg==,iv:7+SfJ6lTzVtGEOVdkS2UmA1x3YJ2vOj1RZQN17qYxNo=,tag:zjQRECxhvBuC7qoH0IEwyQ==,type:bool]
    - ENC[AES256_GCM,data:Pr2m1Zo=,iv:glceraDMcovK62eejH/O+ulE3Yn0czPzBmL+gOBTz10=,tag:VczXhzIIt6ZS09VZkfIzrw==,type:bool]
ANTHROPIC_API_KEY: ENC[AES256_GCM,data:kFvkl5QdJ3mOECDZSWkmkCJOmJRJ8/KFje6cs6fay9exOcLPTll0bz9iBdZEG6Mfa7y+LAZLTQoRYL14b4he+cHC/+VJk8C/GXZkTDWBm55mxc8NilvxGzHBrG6ycoxbfgZJtZnOfRrqa5cK,iv:PIBYc4Iwfl+hs2BB2JQ/Pf0B42FlpOnZZRQKhYYhM4k=,tag:jHpvNDz1AK5mSWVPWTWi5w==,type:str]
sops:
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteG94OFJXRlNnZmgwTGkx
            SlZJcUlSTHBscnAzRkdRTjRPeHdCR3RxaHdNClRDYkFnalVFblJROUZQT1V2VkJX
            VDcxSG02YXBpaUJCVFZiSFp0ZytEY0EKLS0tIGNaTVFFMzZFamc1RExhNlg0MjJw
            bWluUTREL1AxK3Fhc3pjajVVb0hoM3MKDAZcPZt/h7vkalcz8uIkXEx58GW+ieKH
            +PTsh1DJ7Qfze94GLk9vwhgDP9EiNmHFDbRmRI+Yxfyn2e3z+HBfmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a3depj56m3sy0pcp9yywv6flv4rv5n4vx2sh8qey28p8mpq9eumsyrvyc9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZXFtRFRyT1IyNEovWlo1
            TWRPY0lvTzBUd3Qxd0xRTGh6cW8raWJKdFR3Ckh1TXFaMGFDeHRPaEFuSnJ0UGgy
            TEdXeGxubGk1TDRWRjZHTi94Ti9YTlEKLS0tIGNsNzUvRjJSeFM3cmJ3RDF3K0Ev
            eEcxaDdsLzFkc0VhbTk2b3NBaXNsbkkK/ulByClXQMyP1pCu36K5GZs3tIAWxB4D
            j+sVEXmJw64Mn1bALjkroO+w4cjvSYFnbg7OidP2Rk/ePrzqA4bgNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-12T13:39:03Z"
    mac: ENC[AES256_GCM,data:0RJn5NtDdTL+PAcSj6z+wEb5metH4eSVqZlE8tihl3Hc6dadR6ZtQLKtyW4CV+jImGMv7foLHmu9m2arT9JMACctb0elWhW4PpskV9eUpgAIX6LL+pLbcjjUJwlgnnhbNxUTli7Y9Z+dpgtMfQRlbBj+1epABflmNMW+5bX9m7I=,iv:KTp0yx3Mkhqq0PXbH0WQWVO3JOYky8fCOv72C6RMtVU=,tag:DVbkVs3xfYZM2EaFw9MBiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
