[package]
name = "app"
version = "0.1.0"
authors = ["knoff <selby@niko.ink>"]
edition = "2018"


#[features]
#default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.92"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
#console_error_panic_hook = { version = "0.1.7", optional = true }
#noise = "0.9.0"
#web-sys = { version = "=0.3.65", features = ["CanvasRenderingContext2d", "ImageData"] }
web-sys = { version = "0.3.65", features = ["Document", "Element", "HtmlCanvasElement", "CanvasRenderingContext2d", "Window"] }
js-sys = "0.3.65"
yew = { version = "0.21.0", features = ["csr"] }
gloo = "0.11.0"
reqwasm = "0.5.0"
yew-mdx = "0.1.0-alpha.1"
roxmltree = "0.19.0"
gloo-utils = "0.2.0"
pulldown-cmark = "0.10.3"
gloo-timers = "0.3.0"
yew-router = "0.18.0"
palette = "0.7.6"
gloo-net = "0.6.0"
serde = "1.0.204"
wasm-bindgen-futures = "0.4.42"



[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = 3
