[package]
name = "marki"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
genanki-rs = "0.4.0"
pulldown-cmark = "0.13.0"
regex = "1.11.3"
syntect = { version = "5.3.0", default-features = false, features = ["default-fancy", "html"] }
walkdir = "2.5.0"
