hello: ENC[AES256_GCM,data:Y7+vnyBBY33Xp4pPQt9Ms/uK9qaunZkrMtIWPYy+/ht+wdWJv7DFisgSLQ==,iv:gR6Gjb2KeTKGn0/k1+kHm6hQv2xzHfy4SmXRMHcT52M=,tag:SkuxYm3SnExIh9l8FpjefQ==,type:str]
example_key: ENC[AES256_GCM,data:TrUuIAXj4blmTNBsvw==,iv:+Bqv+IiFtiSL5IRPQNsiAvNLjZFOrsMgkEpfjBqC2h0=,tag:UqE8IjRaOjZTOdki8OPAJQ==,type:str]
#ENC[AES256_GCM,data:lvU4dYETM9pmMzKnrYlbMg==,iv:XiMmbTD0tVPbvF3G1SX/Vb4WLT7qSHAHTuMLJCgoWYA=,tag:sqjk/O4p89AK286c1VRe1w==,type:comment]
example_array:
    - ENC[AES256_GCM,data:3zE4K3H7G6YsQdHFbJ0=,iv:QG0ajxBb7+Rqcg0bBu0IIemNQKDNWcWvyhbu9CZ2bUw=,tag:PS7WfsBEDv/fM4noyF+yzw==,type:str]
    - ENC[AES256_GCM,data:4UhD6jisturEERITSMU=,iv:sQA+OpsXsoBsYYzIpEClDJ+Kuu3FR8P6nUd9DVnXbrc=,tag:TQrbC3+WLseirmT1WD7NhA==,type:str]
example_number: ENC[AES256_GCM,data:msPHxuHTCx3qRg==,iv:MQbvCC0M5doYTe7Tum1sPGDZK3g1YtYQhzZzvoxsfN0=,tag:ZOy7Nwy6Dz460IkGFMD5vw==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:k5Vnqg==,iv:bwqqMCUQXS5XxTTuSrKN4a45a1/7GnvPujCGszRi/Cc=,tag:PK1vxpJZsnmbcNOQS6KYXg==,type:bool]
    - ENC[AES256_GCM,data:f9bum9c=,iv:u/z0DgK5DdL+g+/j+STx94P/JRSdISrNzNhz7qI6MOk=,tag:ZMJOXi+94APw5+gxbmZonQ==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbkNUdkEzSFNqTHM0K1o0
            OFZ4Wm16SHZqWE95WDZJOXNZM0hhQU5MQlFrCkl3eW5GTkxYR0QxTXNmY2MrRjRI
            Q2dxb0k3N295RHlUUmRLdmJHMFFoVUUKLS0tIGtkazVYK0lRNUF6d1Z2dkNwRGVn
            TkttN3dMVHFzdXg4c3liU00wS3NYM1UKXroS2CIrbumB3AMa+n30hEXpT+X8YHhm
            tUyXG1/LRclZBc8WlijMA4CPnIAPW9hNJyp04bkeeOTgaLAFiOMcRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
    lastmodified: "2026-06-15T20:57:33Z"
    mac: ENC[AES256_GCM,data:xO95/UhFkXxWOg56MhX7OnlGvUlD2Ohz6cFZC2/Z0GHqO58+y+/Y2In1Q96IMjvX4rdWLFSVksuJcX0SHSHvWn1slDhWNIvlhr5JT7HNyklnJsaw5SoWopQ2CyxIpFKF+vXa6U29tlAZFgDjpkSyEb4xhloRh0kOZLfs2IQokr4=,iv:vPi+Rhd8d7Q8oFkcDZckIgpM1nh7RCWQrLooM++47xg=,tag:kEuIP6DbbXBczRRuK672+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
