hashedpassword: ENC[AES256_GCM,data:G+feBGq+x7TqXooQbryS43m58UyY4LBXw3yuuLXq9G9ovzkRPcQmWid/8Asm88wpIghRu57gNw+ii6TeJqVwB0QOMs/0LV6Zww==,iv:+bgvLQBB49JF7CrEXOldMBXimwuZyC/O8lhI08BDtjg=,tag:KstKE3OHLfbphsmbxuj93A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbkNUdkEzSFNqTHM0K1o0
            OFZ4Wm16SHZqWE95WDZJOXNZM0hhQU5MQlFrCkl3eW5GTkxYR0QxTXNmY2MrRjRI
            Q2dxb0k3N295RHlUUmRLdmJHMFFoVUUKLS0tIGtkazVYK0lRNUF6d1Z2dkNwRGVn
            TkttN3dMVHFzdXg4c3liU00wS3NYM1UKXroS2CIrbumB3AMa+n30hEXpT+X8YHhm
            tUyXG1/LRclZBc8WlijMA4CPnIAPW9hNJyp04bkeeOTgaLAFiOMcRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
    lastmodified: "2026-07-13T20:02:27Z"
    mac: ENC[AES256_GCM,data:0fZ4GP8dNN6ht3xM9HHQaQO/wA2e+Rtm6RMLpsuHuo57GHfo/rcF5LJR2wX8Yw36lb2A8OxdVhm9rB6oSXt65Zmdq4K2syymLvAxm7FweezwOnCMb4CC39erCcoMqD8yLS/6FRy/g0gE3rgyaF+3fTLpLKdNqAHyNfC+gx3ueuI=,iv:h0yuju0J6nLYWg8g4yPm8hYJyRsKzQzEjZ/KNG2GrPY=,tag:bH8MdVMBVM2i/Rr7IbG7qw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
