[package]
name = "cli-ai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
arboard = "3.6.0"
clap = { version = "4.5.41", features = ["derive"] }
futures-util = "0.3.31"
llm = "1.3.1"
regex = "1.11.1"
reqwest = { version = "0.12.22", features = ["json", "stream"] }
rig = "0.1.0"
schemars = "1.0.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
toml = "0.9.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
