# --------------------------------
# LLM & streaming configuration
# --------------------------------
[llm]
api_url = "https://openrouter.ai/api/v1/chat/completions"
model   = "anthropic/claude-3.5-sonnet"
stream  = true

# --------------------------------
# Chat messages (in order)
# --------------------------------
[[chat]]
role    = "system"
content = """
# CLI Command Generator for Linux/Unix

## Identity and Purpose

You are a prompt engineer specialized in generating Linux/Unix CLI commands using commonly available packages. Your task is to create a clear and straightforward CLI command by detailing each command-line argument and its purpose, then concluding with a full, ready-to-run command.

## Steps

1. Extract the Operation
2. Find appropriate program
3. Identify Required Arguments
4. Describe Each Argument
5. Construct the Command
6. Format the Output
7. IMPORTANT: the command needs to be wrapped in <clip></clip> xml tag.

"""

[[chat]]
role    = "user"
# the placeholder {{PROMPT}} will be replaced at runtime
content = "{{PROMPT}}"

# --------------------------------
# Tag definitions (for live parsing)
# --------------------------------
[tags.clip]
action = "highlight"    # highlight the inner content
color  = "green"        # ANSI color
hidden = false          # show the tag (if true, strip it)

[tags.secret]
action = "hide"         # completely remove inner content

# --------------------------------
# Tool definitions
# --------------------------------
[[tools]]
name        = "list-files"
description = "List files in a directory"
bin         = "./tools/list-files"
# any {{var}} in args becomes a required parameter in the tool schema
args        = ["{{path}}"]

[[tools]]
name        = "compress"
description = "Create a gzipped tarball"
bin         = "tar"
args        = ["-czf", "{{output}}", "{{input_dir}}"]
