// OpenCode plugin for axiom-ledger.
//
// A cited, attributed ledger of durable facts about a project -- the kind
// of thing a sub-agent works out once (e.g. "hyprkan rules are generated by
// lib/key-layers.nix, not hand-written") that every future agent, including
// parallel sub-agents that never see each other's context, would otherwise
// have to re-derive. Not a session log: assertions with a source and a
// status.
//
// Two tools:
//   axiom_post -- append a claim (or amend an existing one by id)
//   axiom_get  -- fetch full records by id and/or substring query
//
// Storage: one append-only JSONL file per JAIL_START_DIR (the jail's shared
// root across all mounted projects -- see opencode-bubblewrap), under the
// jail's persistent ~/.local/share/opencode dir. Two record shapes share
// the file:
//   post:  {id, t, agent, status, claim, source, why, scope, src?, parents?}
//   amend: {amends, t, agent, status?, note?}
// Reading folds the log: for each id, the post plus the latest amend (by
// t) determines its current status/note. Nothing is ever deleted --
// append-only means concurrent writers from parallel sub-agents can never
// clobber each other (a single appendFileSync under 4KB is atomic on
// Linux), and it means there is no destructive tool for a cheap model to
// misuse. "Retiring" an axiom is amending it to status "retired": it stops
// being surfaced (hints, default listings) but stays axiom_get-able by id,
// reversible by amending again.
//
// Scope: NOT `ctx.worktree`. opencode resolves worktree by walking UPWARD
// from the launch dir for a `.git` (packages/core/src/git.ts); it never
// discovers repos nested below. The jail launches multi-project sessions
// at the deepest common ancestor of the mounted repos (opencode-bubblewrap
// default.nix), which usually isn't a repo itself -- so `ctx.worktree`
// collapses to "/". Instead, each axiom's `scope` is derived at post time
// from its own cited `source` path, walking UP from that file to the
// nearest `.git`. A source with no resolvable file (a command, a URL) gets
// scope "*" (global/cross-repo). `scope` is metadata for display and for
// narrowing an explicit axiom_get search -- it does NOT gate what
// surfaces automatically. An earlier version filtered by "is this repo
// mounted in the session", but every jailed session mounts every repo it
// was given for the whole session, so that filter never actually excluded
// anything -- dead weight wearing a scoping mechanism's clothes.
//
// Surfacing: no always-on injected index. That was tried and rejected --
// pushed into every step regardless of relevance, it charged tokens on
// every turn (transient re-injection was structurally forced: the message
// array plugins see is re-fetched from storage each loop iteration, so
// nothing short of every-step injection would even render) for axioms
// about repos or files you might not be touching this session. Instead,
// axiom-ledger hooks `tool.execute.after` on `read`/`grep`/`glob` (fires
// for built-in tools too, not just plugin ones) and appends a one-line
// hint to a tool result when that result touches a file some axiom cites.
// The trigger IS the relevance signal -- no separate subscribe step, no
// scope filter guessing what you care about. Cost is zero on any read
// that touches nothing cited, and the hint rides inside an already-cached
// tool result rather than a fresh per-step message. Axioms with no file
// citation (a command, a URL) never get a hint; they're reachable only via
// `axiom_get`, and `jail-context.md` tells agents that tool exists.
//
// Staleness: each axiom citing a real file also captures a content
// "anchor" -- the cited lines, trimmed and dedented -- plus size/mtime at
// post time. Checking freshness stats first (cheap, no read) and only
// falls through to reading + searching for the anchor when size/mtime
// changed. Finding the anchor text anywhere in the current file (even at a
// different line) counts as fresh with reported drift; not finding it at
// all flags the axiom `!changed`. This is deliberately a content search,
// not a line-number or whole-file hash: a hash flags any edit anywhere in
// the file (false positives from unrelated changes) and a bare line range
// flags any code inserted above the citation (false positives from
// drift). Anchoring survives both. It is NOT an AST-aware diff -- no
// dependency, no per-language patterns, and critically, no silent-failure
// mode: a wrong ast-grep pattern matches nothing and never flags again,
// whereas a wrong anchor just doesn't match and correctly flags for
// re-verification. Never written back to the ledger -- computed fresh
// every time, so the plugin stays a reader of the codebase, not an author
// of judgments about it. Since a hint only fires when the cited file is
// already being read, the freshness check gets it from page cache for
// free -- no extra I/O beyond the read that was already happening.
//
// No pruning, no post cap, no free-text tags -- see the design discussion
// this shipped from. Ranking (verified > refuted > unverified) plus a
// 3-hint-per-result cap is what keeps a flood of unverified junk from
// drowning out a genuinely relevant hint; scope is derived from the
// citation rather than declared, so it can't fragment the way a free-text
// tag would; a claim's own text is its search surface for everything
// else, via axiom_get.

import { createRequire } from "node:module";
import {
  appendFile,
  mkdir,
  readFile,
  rename,
  stat,
  writeFile,
} from "node:fs/promises";
import { createHash } from "node:crypto";
import { homedir } from "node:os";
import { dirname, join, basename } from "node:path";

function loadZod() {
  const require = createRequire(
    (process.env.HOME || "/root") + "/.config/opencode/package.json"
  );
  return require("zod").z;
}

const COMPACT_THRESHOLD = 1024 * 1024; // 1MB
const STATUS_RANK = { verified: 0, refuted: 1, unverified: 2, retired: 3 };
const STATUSES = ["verified", "refuted", "unverified", "retired"];

const ANCHOR_MAX_LINES = 80;
const ANCHOR_MAX_CHARS = 4096;
const MAX_SCAN_LINES = 20000; // safety cap on the drift-search fallback
export const HINT_CAP = 3; // most axiom hints a single tool result will carry

function ledgerPath(startDir) {
  const hash = createHash("sha256").update(startDir).digest("hex").slice(0, 6);
  const dir = join(homedir(), ".local", "share", "opencode", "axioms");
  return join(dir, `${basename(startDir) || "root"}-${hash}.jsonl`);
}

function randomId() {
  return Math.random().toString(36).slice(2, 6).padEnd(4, "0");
}

function daysAgo(iso) {
  const ms = Date.now() - new Date(iso).getTime();
  return Math.max(0, Math.floor(ms / 86400000));
}

function resolvePath(p, cwd) {
  return p.startsWith("/") ? p : join(cwd, p);
}

// Trim trailing whitespace per line, then strip the common leading
// indentation across non-blank lines. Lets an anchor survive the common
// refactor of wrapping cited code in an if/try block (which reindents
// everything without changing its meaning) without also swallowing real
// content changes -- unlike collapsing all whitespace, which would.
function normalizeBlock(lines) {
  const trimmed = lines.map((l) => l.replace(/[ \t]+$/, ""));
  const indents = trimmed
    .filter((l) => l.length > 0)
    .map((l) => l.match(/^[ \t]*/)[0].length);
  const minIndent = indents.length ? Math.min(...indents) : 0;
  return trimmed.map((l) => (l.length ? l.slice(minIndent) : "")).join("\n");
}

// A citation's file part looks like a path: no spaces, no URL scheme, no
// shell-quoting punctuation. Anything else (a command, a doc URL) safely
// falls through to scope "*" and no staleness/hint tracking -- this is a
// heuristic gate, and the failure mode of guessing wrong here is just
// "no extra tracking for this axiom", not a wrong answer.
const PATH_LIKE = /^[\w@.\/-]+$/;

// Split "path:N", "path:N-M", or a bare path into its parts. Pure --
// exported for tests, no fs access.
export function parseSource(source) {
  const s = String(source || "").trim();
  if (!s) return null;
  const m = s.match(/^(.*?):(\d+)(?:-(\d+))?$/);
  const rawPath = m ? m[1] : s;
  if (!PATH_LIKE.test(rawPath)) return null;
  const startLine = m ? parseInt(m[2], 10) : null;
  const endLine = m && m[3] ? parseInt(m[3], 10) : startLine;
  return { rawPath, startLine, endLine };
}

async function pathHasGit(dir) {
  try {
    await stat(join(dir, ".git"));
    return true;
  } catch {
    return false;
  }
}

async function findGitRoot(startDir) {
  let cur = startDir;
  while (true) {
    if (await pathHasGit(cur)) return cur;
    const parent = dirname(cur);
    if (parent === cur) return null;
    cur = parent;
  }
}

export async function deriveScope(source, cwd, override) {
  if (override) return override;
  const parsed = parseSource(source);
  if (!parsed) return "*";
  const root = await findGitRoot(dirname(resolvePath(parsed.rawPath, cwd)));
  return root || "*";
}

function buildAnchor(lines) {
  const capped = [];
  let chars = 0;
  for (const l of lines.slice(0, ANCHOR_MAX_LINES)) {
    if (capped.length > 0 && chars + l.length + 1 > ANCHOR_MAX_CHARS) break;
    capped.push(l);
    chars += l.length + 1;
  }
  if (capped.length === 0 && lines.length > 0) {
    capped.push(lines[0].slice(0, ANCHOR_MAX_CHARS));
  }
  return normalizeBlock(capped);
}

// Captures what a citation currently points at: size/mtime for the cheap
// stat-gate, plus a normalized text anchor of the cited lines (or the
// whole file, capped, if no line range was given) for the content search.
// Returns null when the source doesn't resolve to a real file -- no
// staleness tracking or hinting for a command or URL citation.
export async function captureSrc(source, cwd) {
  const parsed = parseSource(source);
  if (!parsed) return null;
  const abs = resolvePath(parsed.rawPath, cwd);
  let st;
  try {
    st = await stat(abs);
  } catch {
    return null;
  }
  if (!st.isFile()) return null;
  const text = await readFile(abs, "utf8");
  const allLines = text.split("\n");
  const startIdx = parsed.startLine ? Math.max(0, parsed.startLine - 1) : 0;
  const endIdx = parsed.endLine ? Math.min(allLines.length, parsed.endLine) : allLines.length;
  const slice = allLines.slice(startIdx, Math.max(endIdx, startIdx + 1));
  return {
    path: abs,
    size: st.size,
    mtime: st.mtimeMs,
    line: startIdx + 1,
    anchor: buildAnchor(slice),
  };
}

// Fresh iff size+mtime are unchanged (no read needed), or the anchor text
// is still found somewhere in the file (possibly at a drifted line).
// Never written to the ledger -- recomputed on every check.
export async function checkFresh(rec) {
  if (!rec.src) return null;
  let st;
  try {
    st = await stat(rec.src.path);
  } catch {
    return { fresh: false, reason: "gone" };
  }
  if (st.size === rec.src.size && st.mtimeMs === rec.src.mtime) {
    return { fresh: true };
  }
  let text;
  try {
    text = await readFile(rec.src.path, "utf8");
  } catch {
    return { fresh: false, reason: "gone" };
  }
  const allLines = text.split("\n");
  const anchorLineCount = rec.src.anchor.split("\n").length;

  const windowMatches = (start) => {
    const window = allLines.slice(start, start + anchorLineCount);
    if (window.length < anchorLineCount) return false;
    return normalizeBlock(window) === rec.src.anchor;
  };

  const origStart = rec.src.line - 1;
  if (windowMatches(origStart)) return { fresh: true };

  if (allLines.length <= MAX_SCAN_LINES) {
    for (let i = 0; i < allLines.length; i++) {
      if (i === origStart) continue;
      if (windowMatches(i)) return { fresh: true, drifted: true, line: i + 1 };
    }
  }
  return { fresh: false, reason: "changed" };
}

// Fold the append-only log into current-state records, keyed by id. Each
// post seeds a record (scope/src/etc. included verbatim); each amend
// (matched by `amends`) overwrites status/note and bumps `t`, keeping
// every other original field, including scope and src.
export async function readAll(path) {
  let text;
  try {
    text = await readFile(path, "utf8");
  } catch {
    return [];
  }
  const byId = new Map();
  for (const line of text.split("\n")) {
    if (!line.trim()) continue;
    let rec;
    try {
      rec = JSON.parse(line);
    } catch {
      continue; // one corrupt line must not sink the whole ledger
    }
    if (rec.id) {
      byId.set(rec.id, { ...rec, note: undefined });
    } else if (rec.amends && byId.has(rec.amends)) {
      const cur = byId.get(rec.amends);
      byId.set(rec.amends, {
        ...cur,
        t: rec.t,
        status: rec.status || cur.status,
        note: rec.note,
      });
    }
  }
  return [...byId.values()];
}

// Memoizes readAll() against the ledger file's size+mtime, so a session
// that reads/greps many files (each a candidate hint check) doesn't
// re-parse the whole JSONL log on every single tool call -- only after an
// axiom_post actually changes it. Exported so tests can assert cache-hit
// behavior via reference identity, without mocking fs.
export function createLedgerCache(path) {
  let cached = null; // { size, mtimeMs, records }
  return async function read() {
    let st;
    try {
      st = await stat(path);
    } catch {
      cached = null;
      return [];
    }
    if (cached && cached.size === st.size && cached.mtimeMs === st.mtimeMs) {
      return cached.records;
    }
    const records = await readAll(path);
    cached = { size: st.size, mtimeMs: st.mtimeMs, records };
    return records;
  };
}

// Per-SESSION dedup, not per plugin-instance. The plugin factory is
// cached per DIRECTORY (opencode's InstanceState.get, keyed on
// ctx.directory), and a Task-tool sub-agent's child session inherits the
// parent's InstanceRef rather than getting a fresh one -- so a single Set
// in the factory closure would be shared by the main session and every
// sub-agent working in this directory. That silently suppresses hints for
// parallel sub-agents, which are exactly who the ledger is for: the first
// session to read a file would consume the hint and every subsequent
// fresh-context sub-agent reading the same file would see nothing.
// sessionID is present on both tool.execute hooks (session/tools.ts), so
// keying dedup state on it gives each session (main or sub-agent) its own
// set, without needing any new plumbing.
//
// ponytail: unbounded Map growth over the directory instance's lifetime
// (one Set of ~4-char ids per session, forever) -- fine at the scale of a
// dev jail (kilobytes even after hundreds of sessions); add eviction if
// this ever becomes a long-lived multi-tenant server.
export function createSessionHinter() {
  const bySession = new Map();
  return function hintedFor(sessionID) {
    let s = bySession.get(sessionID);
    if (!s) {
      s = new Set();
      bySession.set(sessionID, s);
    }
    return s;
  };
}

// Nudge to post. Agents reliably under-post: the "post before you finish"
// instruction sits in a system prompt read once, and by the end of a task
// attention is on the build and the summary. So after NUDGE_EVERY
// investigative tool calls with no axiom_post in between, one short
// reminder is appended as a trailing synthetic user message -- appended
// last, and only for that one request (transform output is never
// persisted), so the cached prompt prefix is untouched. Re-fires only after
// another NUDGE_EVERY calls, and resets as soon as the agent posts.
export const NUDGE_EVERY = 15;
const INVESTIGATIVE = new Set(["read", "grep", "glob", "task", "bash", "webfetch"]);
const NUDGE_TEXT =
  "<system-reminder>You have done a fair amount of investigation since your " +
  "last axiom_post. If you established anything non-obvious and durable " +
  "(where something is really defined, how a subsystem wires together, a " +
  "confirmed gotcha), post it now with axiom_post. If not, ignore this " +
  "and do not mention it.</system-reminder>";

// Investigative tool calls since the most recent axiom_post (or ever).
export function sinceLastPost(messages) {
  let n = 0;
  for (const m of messages)
    for (const p of m.parts || []) {
      if (p.type !== "tool") continue;
      if (p.tool === "axiom_post") n = 0;
      else if (INVESTIGATIVE.has(p.tool)) n++;
    }
  return n;
}

// Returns the reminder text or null; `nudgedAt` is per-session state
// (Map sessionID -> call count at last nudge).
export function nudgeFor(messages, nudgedAt) {
  const sid = messages.find((m) => m.info?.sessionID)?.info.sessionID;
  if (!sid) return null;
  const n = sinceLastPost(messages);
  const last = nudgedAt.get(sid) ?? 0;
  if (n < last) nudgedAt.set(sid, 0); // posted since: start over
  if (n < NUDGE_EVERY || n - (nudgedAt.get(sid) ?? 0) < NUDGE_EVERY) return null;
  nudgedAt.set(sid, n);
  return NUDGE_TEXT;
}

async function append(path, rec) {
  await mkdir(join(path, ".."), { recursive: true });
  await appendFile(path, JSON.stringify(rec) + "\n");
  await maybeCompact(path);
}

// Self-healing: once the log grows past 1MB, the next post rewrites it
// folded (dropping retired records), instead of running as a scheduled job
// or a tool an agent has to remember to call.
async function maybeCompact(path) {
  let size = 0;
  try {
    size = (await readFile(path)).length;
  } catch {
    return;
  }
  if (size < COMPACT_THRESHOLD) return;
  const records = (await readAll(path)).filter((r) => r.status !== "retired");
  const tmp = `${path}.tmp-${Date.now()}`;
  await writeFile(
    tmp,
    records.map((r) => JSON.stringify({ ...r, note: undefined })).join("\n") + "\n"
  );
  await rename(tmp, path);
}

function byRankThenDate(a, b) {
  const rankDiff = STATUS_RANK[a.status] - STATUS_RANK[b.status];
  if (rankDiff) return rankDiff;
  return new Date(b.t) - new Date(a.t);
}

// Absolute-path file header line grep.ts emits per matched file
// ("${match.path}:", one per group of match lines -- see grep.ts).
const GREP_HEADER = /^(\/.+):$/;

// Which absolute file paths a read/grep/glob tool result touched. None of
// the three expose a structured path list in `metadata` (grep/glob's
// metadata is just counters); paths live in the `output` text except for
// read, which nests the resolved absolute path at metadata.display.path.
// Pure string parsing against the tools' actual output shapes -- exported
// for tests, no fs access.
export function extractPaths(tool, output) {
  if (tool === "read") {
    const p = output?.metadata?.display?.path;
    return p ? [p] : [];
  }
  if (tool === "grep") {
    const lines = String(output?.output || "").split("\n");
    return lines.filter((l) => GREP_HEADER.test(l)).map((l) => l.slice(0, -1));
  }
  if (tool === "glob") {
    const lines = String(output?.output || "").split("\n");
    return lines.filter((l) => l.startsWith("/"));
  }
  return [];
}

function formatHint(r, fresh) {
  const stale = fresh && !fresh.fresh ? `, !${fresh.reason}` : "";
  return `[axiom ${r.id} (${r.status}, ${daysAgo(r.t)}d${stale}): ${r.claim} -- axiom_get ${r.id}]`;
}

// Picks which axioms to surface for a set of touched paths: excludes
// retired and already-hinted-this-session ids, ranks verified > refuted >
// unverified (newest first), caps at HINT_CAP with an overflow note.
// Returns null when there's nothing to show. `hintedIds` is read-only
// here (the caller marks ids hinted after this succeeds) so a thrown
// checkFresh doesn't leave hinted state half-updated.
export async function computeHints(records, paths, hintedIds) {
  const pathSet = new Set(paths);
  const candidates = records.filter(
    (r) => r.status !== "retired" && r.src && pathSet.has(r.src.path) && !hintedIds.has(r.id)
  );
  if (candidates.length === 0) return null;
  candidates.sort(byRankThenDate);
  const shown = candidates.slice(0, HINT_CAP);
  const lines = [];
  for (const r of shown) {
    lines.push(formatHint(r, await checkFresh(r)));
  }
  if (candidates.length > shown.length) {
    lines.push(`... ${candidates.length - shown.length} more, axiom_get`);
  }
  return { text: lines.join("\n"), shownIds: shown.map((r) => r.id) };
}

// The tool.execute.after hook body, factored out so it's testable without
// the plugin factory (which needs zod resolvable via HOME). Never lets a
// hint failure reach the caller -- a hint is a nice-to-have appended to a
// real tool result, and must never be the reason that result is lost.
export async function tryHint(tool, output, readCachedFn, hintedIds) {
  try {
    const paths = extractPaths(tool, output);
    if (paths.length === 0) return;
    const records = await readCachedFn();
    const result = await computeHints(records, paths, hintedIds);
    if (!result) return;
    for (const id of result.shownIds) hintedIds.add(id);
    output.output += "\n\n" + result.text;
  } catch {
    // swallow -- see comment above
  }
}

// V1 plugin shape (`export default { id, server }`), not the bare
// function default every other plugin here uses. Required: opencode's
// loader (plugin/index.ts) only recognizes a bare-function default via
// its legacy fallback path, and that path validates EVERY named export
// in the module -- including HINT_CAP (a number) and __test (a plain
// object) below -- as a candidate plugin function, throwing "Plugin
// export is not a function" the moment it hits one that isn't. The V1
// object form is detected and returned before that fallback ever runs,
// so co-located non-function exports are never inspected. `id` is
// mandatory for directory-scanned ("file source") plugins specifically
// (shared.ts: resolvePluginId throws "must export id" otherwise) --
// any non-empty string satisfies it, no uniqueness check exists.
async function server(ctx) {
  const z = loadZod();
  const startDir = process.env.JAIL_START_DIR || ctx.directory;
  const path = ledgerPath(startDir);
  const readCached = createLedgerCache(path);
  const hintedFor = createSessionHinter();
  const nudgedAt = new Map();

  return {
    "experimental.chat.messages.transform": async (_input, output) => {
      try {
        const text = nudgeFor(output.messages, nudgedAt);
        if (!text) return;
        const sessionID = output.messages.find((m) => m.info?.sessionID).info.sessionID;
        output.messages.push({
          info: { role: "user", id: `axiom-nudge-${Date.now()}`, sessionID },
          parts: [{ type: "text", text, synthetic: true }],
        });
      } catch {}
    },

    tool: {
      axiom_post: {
        description:
          "Post a durable, cited fact about this codebase to the shared axiom " +
          "ledger, or amend an existing one. Not a session log -- axioms are " +
          "claims other agents (including parallel sub-agents that never see " +
          "your context) can reuse without re-deriving. Every axiom is " +
          "auto-stamped with the posting agent's name and a timestamp; you " +
          "cannot claim verification you didn't do. Require a `source` " +
          "(file:line or command) and a one-line `why` -- an axiom without a " +
          "citation is not worth posting. A file:line source also makes this " +
          "axiom surface automatically as a hint whenever any agent later " +
          "reads/greps/globs that file. Which repo an axiom belongs to is " +
          "derived automatically from `source` (walking up to its nearest " +
          ".git) -- pass `scope` only to override that when it's wrong. To " +
          "retire, correct, or confirm an existing axiom, pass `amends` with " +
          "its id rather than posting a duplicate.",
        args: {
          claim: z
            .string()
            .optional()
            .describe("The fact, stated plainly. Required for a new post."),
          source: z
            .string()
            .optional()
            .describe(
              "Where this comes from: file:line, a command you ran, or a doc " +
                "URL. Required for a new post. A file:line citation also " +
                "seeds automatic staleness tracking, repo scoping, and hints " +
                "on future reads of that file."
            ),
          why: z
            .string()
            .optional()
            .describe(
              "One line of reasoning connecting the source to the claim. " +
                "Required for a new post."
            ),
          scope: z
            .string()
            .optional()
            .describe(
              "Override the repo this axiom applies to (normally derived " +
                "from `source`). Pass \"*\" for a fact that applies across " +
                "every repo (a tool's behavior, an API quirk)."
            ),
          parents: z
            .array(z.string())
            .optional()
            .describe("Ids of axioms this one was built on, if any."),
          supersedes: z
            .string()
            .optional()
            .describe("Id of an axiom this new post replaces (that id gets retired)."),
          amends: z
            .string()
            .optional()
            .describe(
              "Id of an existing axiom to amend instead of posting new. Use " +
                "with `status` and/or `note`."
            ),
          status: z
            .enum(STATUSES)
            .optional()
            .describe(
              "With `amends`: the new status. verified = confirmed true, " +
                "refuted = confirmed false (ranks high so others don't repeat " +
                "the mistake), retired = no longer relevant."
            ),
          note: z.string().optional().describe("With `amends`: why the status changed."),
        },
        async execute(args, context) {
          if (args.amends) {
            const records = await readCached();
            if (!records.some((r) => r.id === args.amends)) {
              return `Error: no axiom ${args.amends} in this project's ledger`;
            }
            await append(path, {
              amends: args.amends,
              t: new Date().toISOString(),
              agent: context.agent,
              status: args.status,
              note: args.note,
            });
            return `Amended ${args.amends}${args.status ? ` -> ${args.status}` : ""}`;
          }

          if (!args.claim || !args.source || !args.why) {
            return "Error: `claim`, `source`, and `why` are all required for a new axiom (or pass `amends` to update an existing one)";
          }

          const id = randomId();
          const status = ["build", "plan"].includes(context.agent) ? "verified" : "unverified";
          const scope = await deriveScope(args.source, context.directory, args.scope);
          const src = await captureSrc(args.source, context.directory);
          await append(path, {
            id,
            t: new Date().toISOString(),
            agent: context.agent,
            status,
            claim: args.claim,
            source: args.source,
            why: args.why,
            scope,
            ...(src ? { src } : {}),
            ...(args.parents?.length ? { parents: args.parents } : {}),
          });
          if (args.supersedes) {
            await append(path, {
              amends: args.supersedes,
              t: new Date().toISOString(),
              agent: context.agent,
              status: "retired",
              note: `superseded by ${id}`,
            });
          }
          return `Posted ${id} (${status}, scope: ${scope === "*" ? "global" : basename(scope)})`;
        },
      },

      axiom_get: {
        description:
          "Load full axiom records (source + reasoning + staleness), by id " +
          "and/or a substring search over claim+source text. Searches the " +
          "whole ledger by default -- pass `scope` to narrow to one repo's " +
          "path, or \"*\" for global-only axioms. File-cited axioms already " +
          "surface as a hint when you read/grep/glob that file; reach for " +
          "this mainly to check a hint's staleness, or to look up an axiom " +
          "with no file to hang a hint on (a command or doc citation).",
        args: {
          ids: z.array(z.string()).optional().describe("Specific axiom ids to fetch."),
          query: z.string().optional().describe("Substring to search for in claim or source."),
          scope: z
            .string()
            .optional()
            .describe("Narrow the search to one repo's path, or \"*\" for global-only axioms."),
          parents: z
            .boolean()
            .optional()
            .describe("Also pull one level of the fetched axioms' parents."),
        },
        async execute(args, context) {
          const records = await readCached();
          if (records.length === 0) return "(no axioms recorded yet)";

          const idSet = new Set(args.ids || []);
          const needle = args.query?.toLowerCase();
          const pool = args.scope ? records.filter((r) => r.scope === args.scope) : records;

          let matched;
          if (idSet.size || needle) {
            matched = pool.filter(
              (r) =>
                idSet.has(r.id) ||
                (needle &&
                  (r.claim.toLowerCase().includes(needle) ||
                    r.source.toLowerCase().includes(needle)))
            );
            if (idSet.size) {
              // Explicit id lookups always bypass the scope filter.
              for (const r of records) {
                if (idSet.has(r.id) && !matched.includes(r)) matched.push(r);
              }
            }
          } else {
            matched = pool;
          }
          if (matched.length === 0) return "(no axioms match)";

          if (args.parents) {
            const have = new Set(matched.map((r) => r.id));
            const parentIds = new Set(matched.flatMap((r) => r.parents || []));
            for (const r of records) {
              if (parentIds.has(r.id) && !have.has(r.id)) matched.push(r);
            }
          }

          const rendered = await Promise.all(
            matched.map(async (r) => {
              const scopeLabel = r.scope === "*" ? "global" : basename(r.scope);
              const lines = [
                `${r.id} [${r.status} ${daysAgo(r.t)}d ${r.agent}, scope: ${scopeLabel}] ${r.claim}`,
                `  source: ${r.source}`,
                `  why: ${r.why}`,
              ];
              if (r.parents?.length) lines.push(`  parents: ${r.parents.join(", ")}`);
              if (r.note) lines.push(`  note: ${r.note}`);
              if (r.src) {
                const fresh = await checkFresh(r);
                if (!fresh.fresh) {
                  lines.push(`  staleness: !${fresh.reason} -- cited code no longer matches, re-verify`);
                } else if (fresh.drifted) {
                  lines.push(`  staleness: fresh, but source moved to line ${fresh.line}`);
                } else {
                  lines.push(`  staleness: fresh`);
                }
              }
              return lines.join("\n");
            })
          );
          return rendered.join("\n\n");
        },
      },
    },

    "tool.execute.after": async (input, output) => {
      if (input.tool !== "read" && input.tool !== "grep" && input.tool !== "glob") return;
      await tryHint(input.tool, output, readCached, hintedFor(input.sessionID));
    },
  };
}

export default { id: "axiom-ledger", server };

// Exported for tests only.
export const __test = {
  readAll,
  ledgerPath,
  daysAgo,
  parseSource,
  deriveScope,
  captureSrc,
  checkFresh,
  normalizeBlock,
  createLedgerCache,
  extractPaths,
  computeHints,
  tryHint,
  createSessionHinter,
};
