hashedpassword: ENC[AES256_GCM,data:k+alnKQCtgphjpqdh1s7ManIOer7KR476oGrrU4dgPO1lykJkI2Mn4jRzXSQMwv9kENEeJ9svGh6TLnWeiwfWigy1sHNV5HyJg==,iv:xgB5PG/QydJzpkC7EM2SLSzY22DiDvGETA9NjHBvqXI=,tag:UQ08/AQl9G2WSgM9GiJFLg==,type:str]
ha:
    api_token: ENC[AES256_GCM,data:/YrWI8MT7JLNbQOGy4jIwd3N30mXdPHU0AXXCqtxwgWWBZ4A5At9F+rLjDddj4PHCXBnynKsy4phMcKUY0mkKP5YK/84II/wgXuX9FNuZjGoc/mKLmC2Wo826aA7mFUC+wO6uL3vPNHjiRFLprZs5NeZasvt2ptzeK8OmvslZxUSVQJl8l9J/8MJKDlrtNBYZs87wec/ewVdxCvYSPEeMzACMLYmUcWJ5lvCKPaDrPVNUUsPXkcZ,iv:wbwfNzgtCAJnpvWts8dwa1OJM3dMxLDabXNHoNVvA0s=,tag:MzZcDWP7UDuXUnj2TeEV0g==,type:str]
wifi:
    home:
        fritz: ENC[AES256_GCM,data:XAxaxd7e1P6rrKO0+9IXam3L66FDaHom4A==,iv:ZkwgDhHTyrBzaoiSavcco0l/Y3h7lL2/X0/P+cYzxoM=,tag:WfyV0jtJDC9BlQje2/0Rzw==,type:str]
sops:
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUUZWRWtwb3dLM09KTTJI
            c0ticTJkN0NXRU81d2xnNFUwdExKM3cwOURrCnRiR1dlRmltM0o5V0ZIbkhSRk1j
            L2ErMGliNEx5NncxWlB6bVVYcTg1ZDQKLS0tIDZvT1BQdkk5K3R0THB1bW9Na0hS
            cmtuMlQ3TThzNjhyZVN0eDl1bkpqYm8KbaMjL/lmVjDCiue9j8Z+tmej8HpeYWH3
            ubGVh0xvjFAuQcU6/HDm7BFzC6ISKrjgL03LJgIfDQVMoDSdNfckbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2339ke56fkn0svx7jlejcnwdf83hl4tg5vaa7e0aqgnhr7qedqstxcxcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVM0N0S1ZHcS9Bbm14Vys1
            dWpSTnA3S2NydFR6ZzlNbUUzVVA4ZWFiSGpZCm0xUStKNitkSy9TcWJVZ1BkemV2
            Q3g5SGt2RVRWTW1mVU9SdXJIQlNtV0kKLS0tIFdKdWxQalRhOThDL3U5K2lCcmlt
            QWFCNzEzZzA4Q3pvWEFyZXZhSVlzUTgKbOl05ZmyPFMivLpEwK//IPM1Q6mLpgyd
            nLGM8B4PYypZO6pDuAVGMN5dwcDSszQcgKpouc54nWMMnFEYYB7NjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T19:12:25Z"
    mac: ENC[AES256_GCM,data:8tQKzFuDp50FLrB0Ew9b+QuIPnVciPYLsbLo0tFTQYrwfHG1xGN3Aj3KdgKgJEl0lK+VYqwIxowdIRRIrWId32dIpiuJOzpfhYA2JreAhLpmphacEczd1+3phnxTHj6D3TYpLJMsvivb3tfPB1yHSx+SqA82Zy6OlBpiVedYhPg=,iv:/YMvSXvFYXNiVDw+8Obd113Sov+wDNReVX6lY/AqLHY=,tag:EPO9i3Cduqv3rIbvB91WOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
