hashedpassword: ENC[AES256_GCM,data:k+alnKQCtgphjpqdh1s7ManIOer7KR476oGrrU4dgPO1lykJkI2Mn4jRzXSQMwv9kENEeJ9svGh6TLnWeiwfWigy1sHNV5HyJg==,iv:xgB5PG/QydJzpkC7EM2SLSzY22DiDvGETA9NjHBvqXI=,tag:UQ08/AQl9G2WSgM9GiJFLg==,type:str]
ha:
    api_token: ENC[AES256_GCM,data:/YrWI8MT7JLNbQOGy4jIwd3N30mXdPHU0AXXCqtxwgWWBZ4A5At9F+rLjDddj4PHCXBnynKsy4phMcKUY0mkKP5YK/84II/wgXuX9FNuZjGoc/mKLmC2Wo826aA7mFUC+wO6uL3vPNHjiRFLprZs5NeZasvt2ptzeK8OmvslZxUSVQJl8l9J/8MJKDlrtNBYZs87wec/ewVdxCvYSPEeMzACMLYmUcWJ5lvCKPaDrPVNUUsPXkcZ,iv:wbwfNzgtCAJnpvWts8dwa1OJM3dMxLDabXNHoNVvA0s=,tag:MzZcDWP7UDuXUnj2TeEV0g==,type:str]
wifi:
    home:
        fritz: ENC[AES256_GCM,data:XAxaxd7e1P6rrKO0+9IXam3L66FDaHom4A==,iv:ZkwgDhHTyrBzaoiSavcco0l/Y3h7lL2/X0/P+cYzxoM=,tag:WfyV0jtJDC9BlQje2/0Rzw==,type:str]
ntfy:
    token: ENC[AES256_GCM,data:U7vS/CJ1L0QyJLDxKyVKifvu47HUFgoXiBW8at/gZ0Q=,iv:pku//9TwFMSg2KK5FMqFaGFenckIArPqqGxjZnElYQc=,tag:oijhrDnBA5ZMcCIGBRkt3Q==,type:str]
services:
    caddy:
        cloudflare-env: ENC[AES256_GCM,data:toFJfAF3uBNq30U5AbWEpieLGChaI61n9DVok7KLHtSDnM0vUhM1g2obKlSTfQ/I5f1jYDmH/mkGvJtDsNUgIRX2ALn8hanq7ZVd,iv:Jard7EHQEwYEpt7bvoWd9KzzRpr9NGTEJYEUMzu06T0=,tag:fYIQDB66APFHaxjNw8Q/iw==,type:str]
    tailscale:
        authkey: ENC[AES256_GCM,data:0l8UsRTxrOZ0DPmRgn76uvIkJfkycZYR67JyXMVewTRwJHefdJPA73xUT3ltFB87,iv:8hca7zdcDzGsgCK7xH3GuyfSKXANeTiV0IcXMYhJjWI=,tag:xc6Lr9P5BDX5TdEPLod4cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUUZWRWtwb3dLM09KTTJI
            c0ticTJkN0NXRU81d2xnNFUwdExKM3cwOURrCnRiR1dlRmltM0o5V0ZIbkhSRk1j
            L2ErMGliNEx5NncxWlB6bVVYcTg1ZDQKLS0tIDZvT1BQdkk5K3R0THB1bW9Na0hS
            cmtuMlQ3TThzNjhyZVN0eDl1bkpqYm8KbaMjL/lmVjDCiue9j8Z+tmej8HpeYWH3
            ubGVh0xvjFAuQcU6/HDm7BFzC6ISKrjgL03LJgIfDQVMoDSdNfckbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVM0N0S1ZHcS9Bbm14Vys1
            dWpSTnA3S2NydFR6ZzlNbUUzVVA4ZWFiSGpZCm0xUStKNitkSy9TcWJVZ1BkemV2
            Q3g5SGt2RVRWTW1mVU9SdXJIQlNtV0kKLS0tIFdKdWxQalRhOThDL3U5K2lCcmlt
            QWFCNzEzZzA4Q3pvWEFyZXZhSVlzUTgKbOl05ZmyPFMivLpEwK//IPM1Q6mLpgyd
            nLGM8B4PYypZO6pDuAVGMN5dwcDSszQcgKpouc54nWMMnFEYYB7NjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h2339ke56fkn0svx7jlejcnwdf83hl4tg5vaa7e0aqgnhr7qedqstxcxcg
    lastmodified: "2026-07-17T18:44:32Z"
    mac: ENC[AES256_GCM,data:+UXKH15hYYq8LtWaF7rl91vEyyoJhUTk6K4ACwTk99xZlHLeC/mC7ZkOp0MW1DNx7O/2q4aezlT5apy9Y+cmTKjqDVL+GojZSeoAinphe9QFPvCt6MMH/LCN3F0qUR6UzVT/urOAPVLug5jl151JYMvjI6FzcF+vCkLCX4ze4DU=,iv:eMeZek/6peOF/WxCv8qHCtbFynBHU+9DaTF7RMhC0ro=,tag:pzTEMUqZ3td22kJr7fTDCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
