[package]
name = "feature-immo24"
version = "0.1.0"
edition = "2021"

[dependencies]
# It depends on our shared state crate
axum = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
app-state = { workspace = true }
tracing = "0.1.41"
reqwest = { workspace = true }
anyhow = "1.0.98"
