-- Behavior harness for the Lua fragment generated by modules/keylayers
-- (see lib/key-layers.nix's `windowRules` + modules/keylayers/default.nix's
-- template). Run via `nix flake check` (checks.<system>.key-layers).
--
-- Stubs Hyprland's `hl` global (the fragment's only external dependency:
-- `hl.on` for the focus callback, `hl.exec_cmd` for the fire-and-forget
-- nc invocation towards kanata), then asserts on the sequence of layer
-- switches produced by a scripted series of focus events.
--
-- Usage: lua key-layers-check.lua <generated-fragment.lua>
local fragmentPath = arg[1]

local switches = {}
local registered = {}
hl = {
  on = function(event, fn)
    registered[event] = fn
  end,
  exec_cmd = function(cmd)
    -- Extract the layer from the ChangeLayer JSON embedded in the command.
    local layer = cmd:match('"ChangeLayer".-"new".-"([^"]+)"')
    assert(layer, "exec_cmd called without a ChangeLayer payload: " .. cmd)
    table.insert(switches, layer)
  end,
}

local fragment = assert(io.open(fragmentPath, "r")):read("a")
assert(load(fragment))()

assert(registered["window.active"], "fragment never registered a window.active handler")

local fire = registered["window.active"]
fire({ class = "firefox" }) -- expect: switch to browser
fire({ class = "firefox" }) -- dedup: same layer, expect no write
fire({ class = "com.mitchellh.ghostty" }) -- expect: switch to terminal
fire({ class = "unknown-app-xyz" }) -- unmatched class, expect: fall back to base
fire({ class = nil }) -- malformed event, expect: ignored
fire(nil) -- malformed event, expect: ignored

local expected = {
  "browser",
  "terminal",
  "base",
}

assert(
  #switches == #expected,
  string.format("expected %d switches, got %d: %s", #expected, #switches, table.concat(switches, ", "))
)
for i, w in ipairs(expected) do
  assert(switches[i] == w, string.format("switch %d: expected %q, got %q", i, w, switches[i]))
end

print("key-layers Lua behavior: " .. #expected .. "/" .. #expected .. " assertions passed")
