-- Behavior harness for the Lua fragment generated by modules/keylayers
-- (see lib/key-layers.nix's `windowRules` + modules/keylayers/default.nix's
-- template). Run via `nix flake check` (checks.<system>.key-layers).
--
-- Stubs Hyprland's `hl` global and Lua's `io.popen` (the fragment's only
-- external dependency, used for the persistent `nc` pipe to kanata) with an
-- in-memory fake, then asserts on the sequence of writes produced by a
-- scripted series of focus events.
--
-- Usage: lua key-layers-check.lua <generated-fragment.lua>
local fragmentPath = arg[1]

local writes = {}
local realPopen = io.popen
io.popen = function(cmd, mode)
  return {
    write = function(_, data)
      table.insert(writes, data)
      return true
    end,
    flush = function() end,
    close = function() end,
  }
end

local registered = {}
hl = {
  on = function(event, fn)
    registered[event] = fn
  end,
}

local fragment = assert(io.open(fragmentPath, "r")):read("a")
assert(load(fragment))()

assert(registered["window.active"], "fragment never registered a window.active handler")

local fire = registered["window.active"]
fire({ class = "firefox" }) -- expect: switch to browser
fire({ class = "firefox" }) -- dedup: same layer, expect no write
fire({ class = "com.mitchellh.ghostty" }) -- expect: switch to terminal
fire({ class = "unknown-app-xyz" }) -- unmatched class, expect: fall back to base
fire({ class = nil }) -- malformed event, expect: ignored
fire(nil) -- malformed event, expect: ignored
io.popen = realPopen

local expected = {
  '{"ChangeLayer":{"new":"browser"}}\n',
  '{"ChangeLayer":{"new":"terminal"}}\n',
  '{"ChangeLayer":{"new":"base"}}\n',
}

assert(
  #writes == #expected,
  string.format("expected %d writes, got %d: %s", #expected, #writes, table.concat(writes, ", "))
)
for i, w in ipairs(expected) do
  assert(writes[i] == w, string.format("write %d: expected %q, got %q", i, w, writes[i]))
end

print("key-layers Lua behavior: " .. #expected .. "/" .. #expected .. " assertions passed")
