-- Behavior harness for the Lua fragment generated by modules/keylayers
-- (see lib/key-layers.nix's `windowRules` + modules/keylayers/default.nix's
-- template). Run via `nix flake check` (checks.<system>.key-layers).
--
-- Stubs Hyprland's `hl` global (the fragment's only external dependency:
-- `hl.on` for the focus/title callbacks, `hl.exec_cmd` for the
-- fire-and-forget nc invocation towards kanata), then asserts on the
-- sequence of layer switches produced by a scripted series of events.
--
-- Usage: lua key-layers-check.lua <generated-fragment.lua>
local fragmentPath = arg[1]

local switches = {}
local registered = {}
hl = {
  on = function(event, fn)
    registered[event] = fn
  end,
  exec_cmd = function(cmd)
    -- Extract the layer from the ChangeLayer JSON embedded in the command.
    local layer = cmd:match('"ChangeLayer".-"new".-"([^"]+)"')
    assert(layer, "exec_cmd called without a ChangeLayer payload: " .. cmd)
    table.insert(switches, layer)
  end,
}

local fragment = assert(io.open(fragmentPath, "r")):read("a")
assert(load(fragment))()

assert(registered["window.active"], "fragment never registered a window.active handler")
assert(registered["window.title"], "fragment never registered a window.title handler")

local focus = registered["window.active"]
local retitle = registered["window.title"]
local CAL = "Week of 27 September 2026 — calendar.google.com"

focus({ class = "firefox" }) -- expect: switch to browser
focus({ class = "firefox" }) -- dedup: same layer, expect no write
focus({ class = "com.mitchellh.ghostty" }) -- expect: switch to terminal
focus({ class = "unknown-app-xyz" }) -- unmatched class, expect: fall back to base
focus({ class = nil }) -- malformed event, expect: ignored
focus(nil) -- malformed event, expect: ignored

focus({ class = "firefox", title = "GitHub — github.com", active = true }) -- expect: browser
retitle({ class = "firefox", title = CAL, active = true }) -- title rule beats class rule: calendar
retitle({ class = "firefox", title = CAL .. " x", active = true }) -- anchored pattern misses: browser
retitle({ class = "firefox", title = CAL, active = false }) -- background window: ignored
focus({ class = "firefox", title = CAL }) -- focusing a calendar window: calendar
retitle({ class = "com.mitchellh.ghostty", title = CAL, active = true }) -- title rule is class-scoped: terminal
retitle(nil) -- malformed event, expect: ignored

local expected = {
  "browser",
  "terminal",
  "base",
  "browser",
  "calendar",
  "browser",
  "calendar",
  "terminal",
}

assert(
  #switches == #expected,
  string.format("expected %d switches, got %d: %s", #expected, #switches, table.concat(switches, ", "))
)
for i, w in ipairs(expected) do
  assert(switches[i] == w, string.format("switch %d: expected %q, got %q", i, w, switches[i]))
end

print("key-layers Lua behavior: " .. #expected .. "/" .. #expected .. " assertions passed")
