{
  pkgs,
  self,
  inputs,
}:
# Validates the kanata + Lua fragment generated by lib/key-layers.nix +
# modules/keylayers against a fixture layer set. Referencing `configFile`
# forces modules/kanata's own checkPhase (`kanata --check`, using the real
# upstream parser) to run during this derivation's build; key-layers-check.lua
# loads the generated Lua fragment (catching syntax errors) and asserts its
# runtime behavior (class -> layer matching, dedup, base fallback,
# malformed-event safety) against an in-memory `hl` stub.
let
  # A fixture home-manager config exercising every keyLayers feature
  # (bulk capsbinds, per-key actions, raw/cmd escape hatches, a fork,
  # binds, and a non-base layer with classes to dedup/match against).
  # Building it end-to-end through homeManagerConfiguration means this
  # check runs the actual production code path, not a copy.
  fixture = inputs.home-manager.lib.homeManagerConfiguration {
    inherit pkgs;
    extraSpecialArgs = { inherit self; };
    modules = [
      self.homeModules.kanata
      self.homeModules.keylayers
      {
        home.username = "fixture";
        home.homeDirectory = "/home/fixture";
        home.stateVersion = "24.05";
        services.kanata.package = pkgs.kanata-with-cmd;
        services.kanata.keyboards.main.port = 12345;
        services.kanata.keyboards.main.extraDefCfg = "danger-enable-cmd yes";
        keyLayers.enable = true;
        # `dbl` is always injected in real configs (see modules/noctalia.nix)
        # and is referenced unconditionally by every generated `cap-<layer>`
        # alias, so the fixture must supply it too.
        keyLayers.extraAliases = ''
          dbl (tap-dance-eager 250 (XX XX))
        '';
        keyLayers.layers = {
          base.capsbinds = {
            ctrl = [
              "a"
              "b"
              "c"
            ];
            keys.h.key = "left";
            keys.f5.cmd = "notify-send hello";
          };
          browser = {
            classes = [
              "firefox"
              "chromium-browser"
            ];
            capsbinds.ctrl = [
              "a"
              "c"
              "f"
              "t"
              "v"
              "w"
            ];
            binds.tab = {
              default = "down";
              shift = "up";
            };
          };
          terminal = {
            classes = [
              "com.mitchellh.ghostty"
              "foot"
            ];
            capsbinds.alt = [ "e" ];
          };
        };
      }
    ];
  };
in
pkgs.runCommand "key-layers-check"
  {
    nativeBuildInputs = [ pkgs.lua5_4 ];
    kanataConfig = fixture.config.services.kanata.keyboards.main.configFile;
    luaFragment = fixture.config.xdg.configFile."hypr/kanata-app-layers.lua".text;
    checkScript = ./key-layers-check.lua;
    passAsFile = [
      "luaFragment"
    ];
  }
  ''
    # $kanataConfig is only referenced to force its build (and thus
    # modules/kanata's checkPhase) as a dependency; nothing here reads its
    # contents directly.
    : "$kanataConfig"
    lua "$checkScript" "$luaFragmentPath"
    touch $out
  ''
