hashedpassword: ENC[AES256_GCM,data:k+alnKQCtgphjpqdh1s7ManIOer7KR476oGrrU4dgPO1lykJkI2Mn4jRzXSQMwv9kENEeJ9svGh6TLnWeiwfWigy1sHNV5HyJg==,iv:xgB5PG/QydJzpkC7EM2SLSzY22DiDvGETA9NjHBvqXI=,tag:UQ08/AQl9G2WSgM9GiJFLg==,type:str]
wifi:
    home:
        fritz: ENC[AES256_GCM,data:XAxaxd7e1P6rrKO0+9IXam3L66FDaHom4A==,iv:ZkwgDhHTyrBzaoiSavcco0l/Y3h7lL2/X0/P+cYzxoM=,tag:WfyV0jtJDC9BlQje2/0Rzw==,type:str]
sops:
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUUZWRWtwb3dLM09KTTJI
            c0ticTJkN0NXRU81d2xnNFUwdExKM3cwOURrCnRiR1dlRmltM0o5V0ZIbkhSRk1j
            L2ErMGliNEx5NncxWlB6bVVYcTg1ZDQKLS0tIDZvT1BQdkk5K3R0THB1bW9Na0hS
            cmtuMlQ3TThzNjhyZVN0eDl1bkpqYm8KbaMjL/lmVjDCiue9j8Z+tmej8HpeYWH3
            ubGVh0xvjFAuQcU6/HDm7BFzC6ISKrjgL03LJgIfDQVMoDSdNfckbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2339ke56fkn0svx7jlejcnwdf83hl4tg5vaa7e0aqgnhr7qedqstxcxcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVM0N0S1ZHcS9Bbm14Vys1
            dWpSTnA3S2NydFR6ZzlNbUUzVVA4ZWFiSGpZCm0xUStKNitkSy9TcWJVZ1BkemV2
            Q3g5SGt2RVRWTW1mVU9SdXJIQlNtV0kKLS0tIFdKdWxQalRhOThDL3U5K2lCcmlt
            QWFCNzEzZzA4Q3pvWEFyZXZhSVlzUTgKbOl05ZmyPFMivLpEwK//IPM1Q6mLpgyd
            nLGM8B4PYypZO6pDuAVGMN5dwcDSszQcgKpouc54nWMMnFEYYB7NjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T19:56:54Z"
    mac: ENC[AES256_GCM,data:+3SRdcE2IIpNjZH9k/yDL/YftyNcNxy42/Zh1aztbBBST8oMe9DgbL/p3zEe74ZvO+JGJ24kEGy0OiAzHmDaWZ/LnC9T1Hu1Tk2/eVxzyIXQqxmP8XJucyw4b4AIjTo6RJnCSdTNHcp3KiJdB0+rZ0aJBRoXXyMn2Eu5asa60VU=,iv:iHDEAvmJIMtkr9DhTro+PhvWgGSwJbodPF7WHyo0quU=,tag:BcN+xjX+gxEsedXl+E3O0g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
