#ENC[AES256_GCM,data:3oNoVY3drgaIDy4DtkxqJcgySm2tf0l2zbza95lsVIj0MypZjso=,iv:rN6Y6lPi2TFd5xwnZhc7E08vfoG6OK7sEqv3AVRxHE0=,tag:Mv7PAfLYLcQF3F7OE11NOw==,type:comment]
example-key: ENC[AES256_GCM,data:QEeDAJuy7x+k5R8/uw==,iv:ISA4a4UEAyejSPyVglvghpsxE/gdWV8ZR6jXQuFf2Ko=,tag:yZsqXuCaWRJSZBYGdKzOWQ==,type:str]
#ENC[AES256_GCM,data:OzrWtcqVAA66IwxrlB6j21s4QD1VRaCJZ7ZUeDExgz0TdBNVKbhNykqOwHGfTSpz+zR67TgScys=,iv:tO+up2KCTrIL6J2jumNDvYO1XgbW2heg3q+MWAwR2fI=,tag:recumlSOV7OjESyorrR/Ew==,type:comment]
#ENC[AES256_GCM,data:eCpwX0dO9Wor7TMMaILEgfUThCpcKr60mOcjrZ6/UMkR+AnCkgjP0l6QdizJAJYebmcB2/hb5RXTXZFkfdZpO9rovOz5p1rg,iv:2gT+rsZIQxe+QA+nnalA+8DV+YNeywWQu2NHtesCDdE=,tag:z4sFoOrXZ3QKfqGJBjcCAg==,type:comment]
myservice:
    my_subdir:
        my_secret: ENC[AES256_GCM,data:DZsQ/KszbatM,iv:z6hGViQDyNrsp4sTrONqfnVG/AO1tBkgKl1g9hoUVPE=,tag:6vS5IVpVIWAvO2fuqW3XCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd3RHNlQzOWJiY0REQVJz
            Q3hHNkpCZTRJcjQrdTRUVDNoTnFtb0EreUZvClY5aUsvdzVucVJ2ZHhRaGJVM0Iz
            K1dwY011Y3NYMFQvc2FFMjdYUVBvUHcKLS0tIEJTamQzSWRlTXYxbWRsU1V6WEdi
            Z3EwaU8zejJNYjI3cS8reGJrSVpjTU0KjRGSBx0ppp/4gyJITdwL1ooCRcUJnuav
            lVktWeZIjXS4kPVpv9751ylIOPixZ7E2HkxSenjmJ5sfW2id0BhRrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kedaufmt9rah4h65gvmml0vfxdjngqsteqqy79rvs4hqs0j9rfaq858cg0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QkFtTFFEOHNvZ3BualE2
            YUlvUDZ6TWlQOHZvMmdjSmdEcUZ3aW9TRkE0CjJncGFKSHZyR0VDQ3Z2SUdWU01K
            a01pZENLMVFpQTMrTFA5Rlhnd0xhOXMKLS0tIG5mWVloSEN2ZkRWZ2lWelhqSDVP
            NGJtWjN1R3pHWkp5WUI4WVhyTjVBVm8KDu9AWF1rJA+xRhHdkuTlT3/yLTbcCFg8
            KMzC6fQWcTlnWv/f4UleBASek9XDbHu2cS3D0koLVvKCwWFpNC90Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T14:29:35Z"
    mac: ENC[AES256_GCM,data:+m/x5uv0Nw7Iquck0iJerIxasaKbMOug3eLM771jRxfUm/a3k3K9UwChw0qN2WjILf0HFjiUdB8riRGt4wcNCJjV8OtZ7r9xrT/nun6WmybbwQi5aV2zWCJG18lEDyfNQe5uKY8zyPQ6aZGRoK7iI3Qr7CXSksTdyvESuj2x7UY=,iv:NVxRa/G1cQfTpg5OIQtsHJDxZK1/EIKteu62TG3Gun4=,tag:3u85jQX9uXv0Lq4gd2AHxA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
