services:
    acme:
        namecheap-user: ENC[AES256_GCM,data:Vv1TyNAF,iv:DjakjQu/Avg/SIeB729IKNMfDibf6hB855ig+lB8nDE=,tag:jJWGvGALMNtPRaGVetDkuQ==,type:str]
        namecheap-key: ENC[AES256_GCM,data:7VQKZY8G74Lbwcy+Xvda9whjzaU+kg2NW/B0VXMsrf0=,iv:A/T88atMMJhHBniJ6zXfWoNtY2sxgKU37iNF4cBwE8U=,tag:gE2EYZ++ktVZvqos8NCIfw==,type:str]
        namecheap-user2: ENC[AES256_GCM,data:hTYVJHx+qw==,iv:t/hH8qu8z0joWQXyk0/1IJb8KPQaocEBsqcJWDhZev0=,tag:unH/N9sLiBqUKrik3Avn1g==,type:str]
        namecheap-key2: ENC[AES256_GCM,data:0FT2JxNTILA7MhlnEhbz1IibLLDB2IzKzgPUdY+hw/M=,iv:I9MskUTltEZsvZumh6uAYwCj9Rvx9sjoFp16Jh99tx4=,tag:KWB1Mbtk9UQd3otv0T45sg==,type:str]
    nextcloud:
        admin-pass: ENC[AES256_GCM,data:NampJOGXgLjlgy6Rk8M=,iv:SYsASQaH/QG2uloag2XmB2cXZhsZ7ZhaAfcWiuILoR0=,tag:bpRtaxftkchZSHvuttYWtA==,type:str]
    wordpress:
        env: ENC[AES256_GCM,data:PajXCyPbbTQg0FYlZpd9EnsDKZc3qB6IE16aR1pqzKDP7myLJ/BuSLzG6HPW/yFO8OgxfFhIfVZmS0WuN3NqgMpx,iv:jE1f1CnipPTp4haq6ySaq6ySTQPCYoi4ANrE810Ygg0=,tag:c4Fh82RT8Id6VMLgxohHuQ==,type:str]
    imap:
        imapfilter_config: ENC[AES256_GCM,data:bWjWd0pWVslGoOIoV2Daob2gwN/QThwdJOHhNW+o/mcUqm1Hpv54oPBiwc3uyFgbrH1oTMyGM9yl/ariwLWc4eHPXd9wJz51Yd8ESK5Qor4k1U3iEE11OTWQNHvJw5kczxDsVBDpeA+XB5aJDf9zaoxjgw==,iv:lRLdNx8SuksGnop5dhMd4+T2V26SXiSXFsqM1dVsGVw=,tag:zuhbTEA7Sr/l+LoO2bG8Xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd3RHNlQzOWJiY0REQVJz
            Q3hHNkpCZTRJcjQrdTRUVDNoTnFtb0EreUZvClY5aUsvdzVucVJ2ZHhRaGJVM0Iz
            K1dwY011Y3NYMFQvc2FFMjdYUVBvUHcKLS0tIEJTamQzSWRlTXYxbWRsU1V6WEdi
            Z3EwaU8zejJNYjI3cS8reGJrSVpjTU0KjRGSBx0ppp/4gyJITdwL1ooCRcUJnuav
            lVktWeZIjXS4kPVpv9751ylIOPixZ7E2HkxSenjmJ5sfW2id0BhRrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kedaufmt9rah4h65gvmml0vfxdjngqsteqqy79rvs4hqs0j9rfaq858cg0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QkFtTFFEOHNvZ3BualE2
            YUlvUDZ6TWlQOHZvMmdjSmdEcUZ3aW9TRkE0CjJncGFKSHZyR0VDQ3Z2SUdWU01K
            a01pZENLMVFpQTMrTFA5Rlhnd0xhOXMKLS0tIG5mWVloSEN2ZkRWZ2lWelhqSDVP
            NGJtWjN1R3pHWkp5WUI4WVhyTjVBVm8KDu9AWF1rJA+xRhHdkuTlT3/yLTbcCFg8
            KMzC6fQWcTlnWv/f4UleBASek9XDbHu2cS3D0koLVvKCwWFpNC90Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T04:46:02Z"
    mac: ENC[AES256_GCM,data:gjmtQaDHXQvbrb/RPB6C2n0F4rqGQUTNEgD0ZtP65MCxf0AI/6LnQR7EpF5FiByCX5R32gGQDCF9fryLulOsONflwgAEWqWy+DfOjyVPdd/PihX4NFhpSxdfH22NeKrNrwCSfjHrCcFMmKWv9+G8ctaac0LH46nEnsu5A41+KP8=,iv:GnW27rsGsgApyHCpiktxIGRkjfK31+F+FQ0cWKTZUuY=,tag:alBl3dKXPGRQMhWfu6RIyQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
