services:
    acme:
        namecheap-user: ENC[AES256_GCM,data:Vv1TyNAF,iv:DjakjQu/Avg/SIeB729IKNMfDibf6hB855ig+lB8nDE=,tag:jJWGvGALMNtPRaGVetDkuQ==,type:str]
        namecheap-key: ENC[AES256_GCM,data:7VQKZY8G74Lbwcy+Xvda9whjzaU+kg2NW/B0VXMsrf0=,iv:A/T88atMMJhHBniJ6zXfWoNtY2sxgKU37iNF4cBwE8U=,tag:gE2EYZ++ktVZvqos8NCIfw==,type:str]
    nextcloud:
        admin-pass: ENC[AES256_GCM,data:NampJOGXgLjlgy6Rk8M=,iv:SYsASQaH/QG2uloag2XmB2cXZhsZ7ZhaAfcWiuILoR0=,tag:bpRtaxftkchZSHvuttYWtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd3RHNlQzOWJiY0REQVJz
            Q3hHNkpCZTRJcjQrdTRUVDNoTnFtb0EreUZvClY5aUsvdzVucVJ2ZHhRaGJVM0Iz
            K1dwY011Y3NYMFQvc2FFMjdYUVBvUHcKLS0tIEJTamQzSWRlTXYxbWRsU1V6WEdi
            Z3EwaU8zejJNYjI3cS8reGJrSVpjTU0KjRGSBx0ppp/4gyJITdwL1ooCRcUJnuav
            lVktWeZIjXS4kPVpv9751ylIOPixZ7E2HkxSenjmJ5sfW2id0BhRrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kedaufmt9rah4h65gvmml0vfxdjngqsteqqy79rvs4hqs0j9rfaq858cg0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QkFtTFFEOHNvZ3BualE2
            YUlvUDZ6TWlQOHZvMmdjSmdEcUZ3aW9TRkE0CjJncGFKSHZyR0VDQ3Z2SUdWU01K
            a01pZENLMVFpQTMrTFA5Rlhnd0xhOXMKLS0tIG5mWVloSEN2ZkRWZ2lWelhqSDVP
            NGJtWjN1R3pHWkp5WUI4WVhyTjVBVm8KDu9AWF1rJA+xRhHdkuTlT3/yLTbcCFg8
            KMzC6fQWcTlnWv/f4UleBASek9XDbHu2cS3D0koLVvKCwWFpNC90Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T15:43:15Z"
    mac: ENC[AES256_GCM,data:50xgMr5FS7OWLwxZk0ICWbPfw31HjSD34mOFcTy+hBBC9xTE0sE9CeAhF5SdUr7QUEQOViErCA5gYqG45E24OFpcEr0dDL8OuxdXua+XrTD4LuLX7BXJL1KMXk1T3RQRv39SMXEb2Dg15pAXybVbq5l1j8zxtxKj7eF4WkgaDCE=,iv:D0Erq64KBX5FJZGLh+rCc3QQbF9gDNLW2NjtjKt7Whs=,tag:dBoGr+LX/OiM15h/omMb4g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
