[package]
name = "axum-website"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
askama = "0.12.1"
askama-filters = "0.1.3"
axum = "0.7.9"
crc32fast = "1.4.2"
lazy_static = "1.5.0"
notify = "8.0.0"
once_cell = "1.20.2"
pulldown-cmark = "0.12.2"
rand = "0.8.5"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.34"
sqlx = { version = "0.8.2", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
tower = "0.5.1"
tower-http = { version = "0.6.2", features = ["fs", "trace"] }
tracing-subscriber = "0.3.18"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
