services:
    tailscale:
        authkey: ENC[AES256_GCM,data:DpOVyNbnEKlfhfkirrDBirM3WOTgJ/EY1vbjsGDtqxr7rfd9RDouY472qZ4/H9YQLMnho5QTa5iNtMSvyNXK2ecAL+haEaHbt8FzZ2lX8aVub/gTOJcirA==,iv:CmiTliR7zmpwJS0XmMqmkrJvn9Dw/4hGtPw7aYinCSg=,tag:WJtFFDuRqxw097iHfpFoJQ==,type:str]
    ntfy:
        token: ENC[AES256_GCM,data:HOZB4SoK2oaP7L0Qi15Km0qm27i1jWmEpyZ2nEuseSM=,iv:dDGIHM7QZQP8V60jfMqkirHAl2tnRGM+EvYVaZx/HAc=,tag:+0ZnNGD+MZjH6VNVZFJOlQ==,type:str]
        publish-token: ENC[AES256_GCM,data:hqGpOW+N4nhIBWr8pOTZWVYXuRLXdiNiA9Q5ApU6qNU=,iv:SD4v0RSgHXwXzqPZSxHJ8Z2DF3DOUP/plLh8LrwPAAM=,tag:iQVGPopxxK0/ZLjf4DAS5A==,type:str]
    minecraft:
        RCON_PASSWORD: ENC[AES256_GCM,data:BK0qXMW+v8/a9kFlEcm1aJZvzrjCh3tq/tgB8waATRC8B7zgM/VoN/fyo0Fj2OVv,iv:7UFEWay01E+0xvEwHhhHfZDa4rWhpX9Y9kzSCwuubOI=,tag:EDkZUyk/tSaF3qstt/O5ew==,type:str]
    nix-autobuild:
        deploy-key: ENC[AES256_GCM,data:myRZ51oJE8euIZiHh3468pmDPMXhJoPGkIJrHNywHA+GPk+WHs/XHngQQ+dfRaHhYLGkByJ055aCwcljQm/vhsi3zxEvwj9O+kU4igWUa3Yi9ZaQCp0XnKWqg+fjuE4CZX1k7bxe2s+htXlQl2q3IJXJRa17hedkvyjeJYe0RgkCtObQNcU9k3cKlsmFAGgYGyU9YzVOLuZEqFP2qM5i/wJht2SzeY0l+J5ZOsE3yxiv0jPPCKDvTaDLdpa1hwdJVd430iLPeZ74EKrl/7Kai8Lplf5qcJDNxZqIBv3sbzdAzw6khBfdz5VKozEABMlxaBduOqKe6AP6kLoqSMQS9Ki3AljcOgwNFILyfjWa3jYBqK0IdT2IMRo3ZeLUJtjgjPFoPC01t4fyLUT9eZklr7iU+TjIMhKBxAV8tV4RyfmcWMIubupMo/dtU17lDUgRkF4YeZf9zMY1OGFLK2KMY/+1YLIuT+vTiUQkHc6AiJa9kQB3EYs7Qd82k2TU2LqAML1wFuggpxilSLrSJygVGl1XHQ+lJBY++FvmSEetE/StxL0=,iv:ycjsoy7DxjCCO5RpvwOP9bxfoYqXP1gvbckSGxY6TOo=,tag:CyQd/lj9Whw0bw+tlTHmqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbGkxdGZDdEdTekhGZ2Z4
            bXJtbmZ5RllubUx1ajhlSTU5M3lEMlFqbEdrCmxQMk93dW1JUG14NkN4YTNNSlF3
            TTBRQ051L1RCeU9qaEJKeW9nRUpPWXMKLS0tIFZCSmFkeklvWk55VUZUcXgrdUND
            aHBJWWF5dUY0SkV1bGpOKzFGcWtNRmsKX8XmNolq3k0yNwUjlkILCoDqoB+HS8Ao
            jZQLfi7Hb4Ee5hULsKPc3DhYxlJKdoz40y8PQ187bozYhcaigl29eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13yardd2dl3ex60phynx4t9sgxm3wy07jxhee6yu2dxzs99ld34ns9zpve7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NVNCcWF2eGdpWml5U0dQ
            SEl4RkF6UXFhcWlHOWV5RjMyUW1HNklxWWkwCndwcGNjQkdGbUU4MGpjazAxNlNX
            d2MwN05LZWJpeEUyWG9xSWsya29pOTAKLS0tIFNjZEVaOFV3QmY1dkFqUW80ZFJm
            aXUvNWFqTjJhUzdaMHArd3ozRzlSZVkKVbJgn4NtLoZpef2EDXwlfzw1X93Ht+4L
            +KyHocDfyOdAdQaFOUvcye0f0JbUY0F49ihtq3Rdcx2PJS+CZpX2zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
    lastmodified: "2026-08-26T19:28:01Z"
    mac: ENC[AES256_GCM,data:nBYoDosdTKsFhsLlUmTBZrWI2RiEFjsjh7Gt3LGIoxe+oXge7V4/gM7rGLV7yV+3RSufwUOuu+p1b+hhPJFCiesOWXoZhavKOTr5SgYq1iFzrigYdwgIeDanL2XPSAaV4PloyKY+H+R1Jm+dXLPIswAe8770/IdeNQ4OWH90h3g=,iv:8E1IVoP4TAvuYj8lyYJRBvd2VWseRqb54KPovL0MKf0=,tag:YhK6KEvonzspt7ubyXjJgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
