hashedpassword: ENC[AES256_GCM,data:k+alnKQCtgphjpqdh1s7ManIOer7KR476oGrrU4dgPO1lykJkI2Mn4jRzXSQMwv9kENEeJ9svGh6TLnWeiwfWigy1sHNV5HyJg==,iv:xgB5PG/QydJzpkC7EM2SLSzY22DiDvGETA9NjHBvqXI=,tag:UQ08/AQl9G2WSgM9GiJFLg==,type:str]
wifi:
    ssid0: ENC[AES256_GCM,data:nOdMpYZm,iv:PzGY7i83zRuT5DinIHcFzZfIXrTpUX54ePpoNCzKDk0=,tag:TggjV+hiR1F4/3e8BAziAQ==,type:str]
    password0: ENC[AES256_GCM,data:awKVc46VGX+wcv6z,iv:8BNCIKG4TDd5CgvgxtgemLeTL0IxcI0LkrqXQdn+NYQ=,tag:IpkBC7CLx8/KAwz5JoIb6g==,type:str]
    envFile0: ENC[AES256_GCM,data:8E+e+81r1AQ7TQoNWAsArpyLhZekAPSSK150fiBgi5g=,iv:gUFx9gnJ1dZ4Dbb7bYBiN+yE74gcdo//acRQtla3xGg=,tag:Kkm0lBY6YIPZ7mjl0Diy4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSVpwYitvQWNMVlVTZmM2
            RHpXWld4Tno4OExUNWticUFHYmcwbXphTlhvClVHSFV5UHY4bVFkMGhrd3pwSzdx
            bE1yT2kraDJad3lNQnRpQ0dSdnRMdkUKLS0tIGpyc3BUSTUzaTZLSG5NMThyQVdK
            eUFzcEFPSHNPOGc4c2sxUzNnelNsaG8Kn39X/Y/4VRmjU2UdYV+wPWcsNFDfidzq
            r354iG62N1DdSxnaZsZNBMIfwqXuTDjKgKBpIcV5ww+YOg40h5d9ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x203sz3zrzjrj094j5dsyrpk4vj6zkp7jgvl6dvgk32nspyjqf9qkyacjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aVloOXFhNWFSOWxDbnpZ
            U29mcmVPU1R0d0EwalFMVVZsRFU0ZXBZRmpZCjZnTlgxSFpmZEhvVDBuMW11aGlX
            STM2cVVucE9SSENwanFON3NEd1M3UzAKLS0tIC8reGIzN2ZURGFERkxKdHVZL0JZ
            K3QwcDlvL3kwbUFtRWpyZHF2SlMrWVkKXPeP1ll+YmK0ESHTNUJxHitKoc4RaNmm
            KXOwmNyOqAR/+quZ19dWERAUyNicV/mtXLXc7DkFzPEj1vKKuz2EfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T12:00:37Z"
    mac: ENC[AES256_GCM,data:NqdJzKT/CqTbMNAWgOd70M/8AUD8BLbr6mRXgzpvBjTRkdGw+nctBZJceUQHBKGBITGs2IUCpomM6NnqPcXpr5HB2U7LwrMx4pXt3XDPacZgexPr4dMz3KMxNZYI4KGSsNRLxeMZ5dYUbipO1YSGxHRUqo76EtOo4XckRRxa4yw=,iv:UAuAdAwb0tcrgHeUzLkQ1ErxNzkSAn3LG9vZVrRTGCs=,tag:0D8CcZSGjbP/LHFoa5xNnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
