hello: ENC[AES256_GCM,data:95BQJDT8XXAsx5hZ6aBHodU6OOA6KNrJa3RYyOBzTJj4Qb0DEFy3yy/ynIHY,iv:zx3KYyYJtmZuw0a7KwiMaLDHrrxekOBEgJ//kaBmwa8=,tag:9nX4RbWh42N5PnVJmAMo6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSVpwYitvQWNMVlVTZmM2
            RHpXWld4Tno4OExUNWticUFHYmcwbXphTlhvClVHSFV5UHY4bVFkMGhrd3pwSzdx
            bE1yT2kraDJad3lNQnRpQ0dSdnRMdkUKLS0tIGpyc3BUSTUzaTZLSG5NMThyQVdK
            eUFzcEFPSHNPOGc4c2sxUzNnelNsaG8Kn39X/Y/4VRmjU2UdYV+wPWcsNFDfidzq
            r354iG62N1DdSxnaZsZNBMIfwqXuTDjKgKBpIcV5ww+YOg40h5d9ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x203sz3zrzjrj094j5dsyrpk4vj6zkp7jgvl6dvgk32nspyjqf9qkyacjt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aVloOXFhNWFSOWxDbnpZ
            U29mcmVPU1R0d0EwalFMVVZsRFU0ZXBZRmpZCjZnTlgxSFpmZEhvVDBuMW11aGlX
            STM2cVVucE9SSENwanFON3NEd1M3UzAKLS0tIC8reGIzN2ZURGFERkxKdHVZL0JZ
            K3QwcDlvL3kwbUFtRWpyZHF2SlMrWVkKXPeP1ll+YmK0ESHTNUJxHitKoc4RaNmm
            KXOwmNyOqAR/+quZ19dWERAUyNicV/mtXLXc7DkFzPEj1vKKuz2EfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T19:37:36Z"
    mac: ENC[AES256_GCM,data:mtVK/Fz8KUblIeEZ/Jun5xWtrhcz8D3jhB9uQDQYvkRjo/WyDbJ74uNeHR+abnm2BQvhFQJaAoC8qB/oGfj/YVTd/tAjfqKTQUVOWHdZtgwyht3bEaWMzEtQYVpPv9z0SNmy9z06ah3ta6OeVuFKhtR/NVU2M52bPcN9f+5AI/Q=,iv:bIN0IzIaOf9cWtmViitHks8vpBJgJC7Ss5gSAx0VxZg=,tag:i5JMeN48jHqoI40zB2XL5g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
