[package]
name = "annotated_text_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
html-escape = "0.2.13"
regex = "1.11.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.11"
