[package]
name = "annotated_text_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
html-escape = "0.2.13"
html5ever = "0.29.1"
markup5ever_rcdom = "0.3.0"
quick-xml = "0.37.2"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.11"
