ANTHROPIC_API_KEY: ENC[AES256_GCM,data:gk9UjFtZpc6xlD2zxmrGhISGSUZr0qOpaR8IpDqTwweX8jKWWWSq8pS/PK05kJYyT/mfLNUSDqmGDTNoWwB6U90/UNlxSjYjMLuqjzqaoFiPJwEfuZkuwm3WV3MO2smKgMK8BZdkVEBJyiwo,iv:mhMa1ToG36HqOI1oWpxER4DcIHcRLP2njepROrVvOpE=,tag:7/FlqEF7MX+/Y+npRCVkRA==,type:str]
backoffice:
    GOOGLE_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:giyBCqOCzr2zzKrpHSO6xxIygwbElgQXOpkCQo4IOJNpMJ82n0IEm4kDCBqAFZ7+xtZSzSS/w6+K/x8boYU+9cBSTU9M1EVy,iv:2rx422OYQvJ8q5zkMiGOAuoil6IHubZ6Jm2eWrr+IUc=,tag:6HibacsrBArc2DGGRs8jBQ==,type:str]
    GOOGLE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XIDE1l4onAfj5gxPzPXzXGjvlZAYa+1zSEIn30g4HWc/I2M=,iv:WMsrq0KMNAYk7sN62VBi4zO1Z2UvsX+p9osVc13qRNM=,tag:lnqUG6wpkEk1SqxJm+LoCg==,type:str]
sops:
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxby9IL3dUcUVOdUxZeWo1
            aGF4RWY4cHJ2ajlUd1lSRW1IK3BKUWRjNldJCk9RbDJoZGtyNUZRRHFxL0NRdnRN
            ZW5uRVYybmt0TStTSk1aVlJkQysraUEKLS0tIHh1ZkJ3V3h5TEozaUlROEptNEV2
            d1EwTDhUQmdTTlNwRWNEbHZFaGNYVk0K8oeYIKOohdBilHs1LerIh+cxexwJzMEA
            A6KiWxKCWUJJJz4+O7IRo1uCugl+K0U/MTBKn3WcVyVxLUiQpw7EMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qhlwc6f4yp7fylpzgeupjydyhvp6snjgvl0j8p6geynww8jzhyvq0cvwu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeDZJTDgvZDB2TzhIYlRa
            V3B3c1pqcjZMbCtvdkNnNWl2WVJuS2NOMVg4CmVwMFk4S2JJdUxJQ1c5SDBRSkx4
            cFd0K3ptZFhKNkdtWlFLWThGVGVmcjQKLS0tIFp5TUVyUndNNndHNVVhME1XRnJi
            UmkwTW8wR2Q3MnlJcGlaZ2FNNldPRGMKOkG3bDn2CX+a+TpO8gkA4RYjhhh5KhFJ
            s/swrRvdC9tVblqMsqokkIg3TjqlFw7Q82hRkpcd6xi8g/hp3G4X7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T14:59:27Z"
    mac: ENC[AES256_GCM,data:yJlY/ndKNP9eUhFBZfjtH3imOoPJuQNbfzpiZ7+258hKburnoQxUpEgMqa70RjLbuCaqX+AyNj4RFFF+7AUwsh9GZjvj0wVmiU+4ZPgJAWhkzE6sjOzRnnDIBfbJqsqehNJRISgjE1M4+5QGjtPrOfxLAUrEdUVB9wQVMdpIgD8=,iv:A+WnUTkue97Wvp4ASV2FmB4YeP/tKKnSeDWiAnDjOEU=,tag:vrZ1KxWHB39D0nHwvnq8Fw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
