hello: ENC[AES256_GCM,data:3EajdRL2GtigKqKL6uXNM9Ov0qgzqM4O8svoT7JkM7hn+MX1UUrM+oRRKHBaRw==,iv:VfM9xEwIs5NX8AK+IxEuLzZOFhR/VuzKKAU2qAIxMxo=,tag:1lHKv24MJXAbTWCeWGZT+Q==,type:str]
example_key: ENC[AES256_GCM,data:OvzlRzm/pPVtrBh5Sg==,iv:2mxtyd0TyrH5MqsEypLwJOND5b1c8QlOPQrsI6dEi8w=,tag:H4Y58v3ZDOMu54ZyYEZPqg==,type:str]
#ENC[AES256_GCM,data:EJgurESXpUP34jGECDLilQ==,iv:/Yx1NqkRBEgrntuSbS6B9ZPhNvjUX3EbcW0EetUsq6c=,tag:IFJ90FVhjwoqpK7eNyVdvw==,type:comment]
example_array:
    - ENC[AES256_GCM,data:x7ofreeH8GgjkQQoTU4=,iv:yVbh3G3lEJM7DsoMXM3iCM1TppZWtJNucWj0tbCkBpk=,tag:dlnsNHF7vOzUYggr242NVw==,type:str]
    - ENC[AES256_GCM,data:0CTApO1YXkcLP4s1CEY=,iv:SbR6scNou3edtbTQiODQjfRAw+6jw1e6FqRfq5hlzYU=,tag:2zgtr9Ig22GG8qQxIlS9tw==,type:str]
example_number: ENC[AES256_GCM,data:hEYt4oABJqUBmw==,iv:Kb5229ol9xai8ATxoFpGLs5saV+259hoen71jUWpsqk=,tag:fgRySh8Cp0jDyG2hR625sA==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:fLbZTg==,iv:2X5H2C4rqf+OyKSDog14ggU6KiTIDE5dVPs4hyoj9+A=,tag:Fk+UneHFjYVUY5G7ZDhagg==,type:bool]
    - ENC[AES256_GCM,data:2jeyk9w=,iv:kpIav46d56yz7gWN2sd2MdamuaZuo9Io0M2J3tuHke0=,tag:1PEQyBKtuQomysO8DZIKZw==,type:bool]
ANTHROPIC_API_KEY: ENC[AES256_GCM,data:gk9UjFtZpc6xlD2zxmrGhISGSUZr0qOpaR8IpDqTwweX8jKWWWSq8pS/PK05kJYyT/mfLNUSDqmGDTNoWwB6U90/UNlxSjYjMLuqjzqaoFiPJwEfuZkuwm3WV3MO2smKgMK8BZdkVEBJyiwo,iv:mhMa1ToG36HqOI1oWpxER4DcIHcRLP2njepROrVvOpE=,tag:7/FlqEF7MX+/Y+npRCVkRA==,type:str]
sops:
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxby9IL3dUcUVOdUxZeWo1
            aGF4RWY4cHJ2ajlUd1lSRW1IK3BKUWRjNldJCk9RbDJoZGtyNUZRRHFxL0NRdnRN
            ZW5uRVYybmt0TStTSk1aVlJkQysraUEKLS0tIHh1ZkJ3V3h5TEozaUlROEptNEV2
            d1EwTDhUQmdTTlNwRWNEbHZFaGNYVk0K8oeYIKOohdBilHs1LerIh+cxexwJzMEA
            A6KiWxKCWUJJJz4+O7IRo1uCugl+K0U/MTBKn3WcVyVxLUiQpw7EMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qhlwc6f4yp7fylpzgeupjydyhvp6snjgvl0j8p6geynww8jzhyvq0cvwu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeDZJTDgvZDB2TzhIYlRa
            V3B3c1pqcjZMbCtvdkNnNWl2WVJuS2NOMVg4CmVwMFk4S2JJdUxJQ1c5SDBRSkx4
            cFd0K3ptZFhKNkdtWlFLWThGVGVmcjQKLS0tIFp5TUVyUndNNndHNVVhME1XRnJi
            UmkwTW8wR2Q3MnlJcGlaZ2FNNldPRGMKOkG3bDn2CX+a+TpO8gkA4RYjhhh5KhFJ
            s/swrRvdC9tVblqMsqokkIg3TjqlFw7Q82hRkpcd6xi8g/hp3G4X7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T19:03:32Z"
    mac: ENC[AES256_GCM,data:m6iVOi4IzAKE/xgQYD756r4jkVkTFxMY3Cy6/92fFMGMa/FEZklgphDx3hMmL/z9rRoJPeZPU4vVAsj0IMnGNfrLPDBDcKdCY0IppKIuG7OP5CmgeNq5RcME8WpVhn+w77LcoqbAqhz8Gj8R6KRhGuD+7IeUnUXxRrD/g4dYT6Q=,iv:w/I/WzTaPxr0omfibQBPnFkFJMmAWmOERFXTsc36RJ8=,tag:nz6hx5f6iPDP7M5GGsX7Ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
