// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");

    // Make askama recompile when templates change
    println!("cargo:rerun-if-changed=templates");
}
