[package]
name = "example-sqlite"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
annotated_text_parser = { path = "./annotated_text_parser" }
askama = "0.12.1"
axum = "0.8.1"
axum-messages = "0.8.0"
http = "1.0.0"
hyper = "1.0.1"
password-auth = "1.0.0"
serde = "1"
sqlx = { version = "0.8.1", features = ["sqlite", "time", "runtime-tokio"] }
time = "0.3.30"
tokio = { version = "1.34.0", features = ["full"] }
tower = "0.5.2"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
base64ct = "=1.6.0"
tower-sessions = { version = "0.14.0", default-features = false, features = [
  "signed",
] }
tower-sessions-sqlx-store = { version = "0.15.0", features = ["sqlite"] }
thiserror = "2.0.0"
axum-login = "0.17.0"
async-trait = "0.1.86"
once_cell = "1.20.3"
tower-http = { version = "0.6.2", features = ["fs"] }
rand = "0.9.0"
openai-api-rs = "5.2.6"
reqwest = "0.12.12"
regex = "1.11.1"
serde_json = "1.0.139"
html-escape = "0.2.13"
