services:
    acme:
        namecheap-user: ENC[AES256_GCM,data:bI+h4I6J,iv:uQRsxSa6S65s4brudjpUbORv4SbxsfnYFNFId0n+hN4=,tag:NI1AOz6RBuuOxMRVRfWmxw==,type:str]
        namecheap-key: ENC[AES256_GCM,data:K8PRjz8d1WGJk8ycZ6WkIE31fKqDS2kMfvSTBuNwIQA=,iv:TYaWgszaBnNE2Zd2oGJD0iYadGuc5oHhn8UP2JBCQA4=,tag:T4w+KSENceztXeMfVtj9vA==,type:str]
        namecheap-user-env: ENC[AES256_GCM,data:fq6dJUk2wPWI/ZwDWK6TPSkh+ee2swP98Q==,iv:E/WJSM7/WEgsfQ+Dl2LZNuZsw5T5C0s1wUmMNYCBrR0=,tag:tyQb3lV1KWNnbVhvna4low==,type:str]
        namecheap-key-env: ENC[AES256_GCM,data:EHPfDTy7RjcCxXL3nyYFzn1CTNuckqALv6YpLYpenNVsl2/F5VY8XA4oDbJ7+npRwck=,iv:4yNzIKyAiGGUqlXFmdGBehE4Xbj+9QrK4gBHv0HFjY4=,tag:J3+yKY6SQrao/SHTUO0Pyw==,type:str]
        envfile: ENC[AES256_GCM,data:LoA+b6iuDf9z/AGH3Nx9LnpEkLiSBxvRojqmvhBhbAMgNaJ4+iCA5Xm2LAWJNHisGt99GFv9k8/xqhGtIBvnvyQ8JQG2y7BO5kHQWcZ2L65BDJDJPKHk/bfg037uQhtdDNzP8qyIY1FY22SmoUBC0+jp9DG4bGI/Ws9zdvfMQczmoby9AeDH95wAvw8brj3WtpzX,iv:8UJ2WEa64cauCDN0EZHjuC4F9oElTTSgslNxa6Z1ByY=,tag:2g5VXUDhOmFQjN/raLojVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYXRPWEJQblNBcVoyajdm
            K0tyMjBjUHJHWFRGbkZaa3B6TzgvUnRDS1c0Cm9oMG5XZUc2R3pZR2Fpb2EvTzJ1
            RkQ2amlXbXYzSnRIWlBaTERyY2lXYW8KLS0tIEtldkR3MG9JR2puNnpnQVB2Z0Vw
            SlBxaDlmbTdWUzU4L0czTnI1VkxsTFUKteL1nglZQUw64HETz76Dd+gtqZ8gsxnc
            S+4AUAUjiHuJKp/bxEClRaxt/czgEhwWFuH/UwgWYzt4+neFdz8mFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age187kd8xwxkpewkrd9jcrhq60vyd8ez93s9nd8jvvju4g4hkc4e4tsx9ck6m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZEpNbkRZcExITWtRMEdN
            Z1FFMmRlVUtJS21MMTVHMFBOem1Nd2FlR2dzCmR6NTNWTUVUZHU0NUNVbWxsUlVK
            bVlyOVZ6dWJtbGZ5dldmUWZrOFRHSTgKLS0tIDc3OFYvODJpMXNYOEtoOFVBVGsw
            UU93K0xkVXBPbFVJTEovemd1UDlNd0UK6LeB6fOkIYGN/IqXe4g6RlJOlffnPe4x
            l+LfhB+WgyGuT8SiK70Ofr0j76e/A7hbhohH/fgHS1SLEOBWocgq/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-30T15:45:55Z"
    mac: ENC[AES256_GCM,data:YP5PYn96gBq9XgYl4qSw2nnH55y9k06KbN7q6FyxBCeoZjuJNSgJtm19sIYXJWy5mMs41gYNBmaQm1ZRKCr4QaJJ6orq9FIc1faWWRDsW991xhVNyIw79Mn4jOd6TRFRBqOnzNSA4HUKEBKTFHiRH0+3K819LxXPcLT7T8VPHf8=,iv:JxLCvATZ8DAHBUEpsAE1dg+CDqGPsUV81P5t9DcFjjY=,tag:6e6aEu0xZn41VdTPW4F8rw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
