services:
    acme:
        namecheap-user: ENC[AES256_GCM,data:lQ7Zu0Is,iv:4suuS2AAxdsgaxhse8CSUaNEPcl+vPfHjjOAVZSbcQs=,tag:u6PjDV6LpV9cTlKlJyvEdw==,type:str]
        namecheap-key: ENC[AES256_GCM,data:ZEFuCZ/aMTm07Mcil3kqv+iyNulFeRpgK2PGC9W27vY=,iv:fqK92PFLxwEpZpBJZQhzstlyJwTv4x2BrCPAtpXcaYo=,tag:rWoWmzAa07c1oliMpgSvNA==,type:str]
        namecheap-user-env: ENC[AES256_GCM,data:lsX76PGlw9oMVDFBzEoLEcX3Y89pK+XKQA==,iv:FbIu3TT73UaZImjsuIfgD74N8o5MSHO9pwYMYmkmwEg=,tag:StCgKa5uZe+IT1JKWUerHg==,type:str]
        namecheap-key-env: ENC[AES256_GCM,data:tdcw91efyc0MITJzRQTREm4tswyttv3yw3iS6LbbxxaTkttPkdZP5CJqh8yJrj9zl88=,iv:25PKIEusPQQU6g11N0Rfgzy/RfZgzoSEsm70WD+U54k=,tag:hLSdUHlz1YP7lGpjfbgciA==,type:str]
        envfile: ENC[AES256_GCM,data:Kt4wv3M4/ImXngExFH+dEGCdcbD1yVjPmYsB9RbD+tun7kWT2SkYhw0in1oP1vOXadU+xXZjtpAywSGxmAbL+5f8Tf3+6a4FPCce3v832bgxOBgjKFilLnnPUuITvVWNeFHBK7ty72TI4YBBMGdwUG7LPaBMKiZ9AFa1p4gSd7URpZ53+KclFfHDXZoD3Zhk3q9h,iv:2chyKtSvvffvXnsL7Dyx9zGmXIvLnzgpQYlozuVUm/8=,tag:dRe403hG9TeO6dRfLHmcQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OFFGdlVFVkljR3cyb0xY
            djRmSEZoeVlGaGNiNTRmMy9ST3FBVVdpZERJCkJrSVFrWEtRVjh1UUhQaXRTOG9X
            c0diMlk4c0tjMmZrNUhCSnVrN3h5RFkKLS0tIGxDRnRCY3greUZtOVNyTFdOTTJV
            bmFxZy9ETFZNaDR5OFArK2pDaEtCaHMK8sLXy8NDhIrzqdGJIKMwMCQ9rWvmZ8uS
            WsN6t1NOjf14f8ocYKBJ1kqU1HFGCTByRq4J/g35UyxiTCT7CVe3jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yfnk76q5velf4ydxvcajm008w42nkfk3tz2euz6666j89pxe2yjqyl4g03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROVQwYW5uTEJjSjFEN2hv
            M0diQzk2S0R6bnVMR2pJazkvN3lOY2ozZlJZCjhnYjllWjF3OHFqSjg5aDRmTHFI
            clhMYXNHdnM1N040eFRJelorQWZibDAKLS0tIDVSbHpYVnRTUmo5bzAwdWF2aTE5
            UEFGY2phdUZKUitpeGhpbmxhTkk4NnMKkB1CQNTymj2JggopsRQLFhcA0Zy3LgNh
            uOg2AmjB2fql7qgcm6nbXSYK/Wl3EW1FXUY1zlpmglSHKEqUishyPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-05T20:37:26Z"
    mac: ENC[AES256_GCM,data:HXoJ2JbfOqFa0w6PXdFTD+Jgpc2rwx6yOxUB4ock6RsYSG6eDF6r7DrBCnUcCLRkj9ZE7KoRScmZDYLrFbL4GBNZSZqzgn6yNaz4jOEt7ZGeYNRh6DJPyeNkethvyTv2VnvkHL1s3lGhr0DVzo1WzjkXON6OuWJFpYDL5hXwkKY=,iv:CEEYozwinmYfsFHMkHPIKbP3sL5t0W7cAp8mPiLPaDc=,tag:zXVdBvJc6oiAOEAAdAErdw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
