[package]
name = "arduino-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0"
panic-halt = "0.2.0"
arduino-hal = { git = "https://github.com/Rahix/avr-hal", branch = "main", features = ["arduino-uno"] }
nb = "1.0.0"

[toolchain]
channel = "nightly"
components = ["rust-src"]
targets = ["avr-unknown-gnu-atmega328"]

[package.metadata.maturin]
python-source = "python"


[target.'cfg(target_arch = "avr")'.dependencies]
panic-halt = "0.2.0"


[build-dependencies]
arduino-hal = { git = "https://github.com/Rahix/avr-hal", branch = "main" }


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

