hashedpassword: ENC[AES256_GCM,data:ALs0pJjN6aLn1LsQMqcnDe1ISb4Z3cGrkb4TVC8AxZklHkA/l20NwxFiTX777CEhiKUNC6vVP5EDbZji96sPZArS5+BvB+yH0w==,iv:hD9HcEZUvwWZr2P4BWCiSG8C8pUC9Rtl5YMjsNfg34k=,tag:/mSDep9kHPS85STgV2LwGQ==,type:str]
ANTHROPIC_API_KEY: ENC[AES256_GCM,data:5UuxRTliAEpL2T8kiD3KGK9WzIM0gqio+xmiFGxUqvN9991sp6xNG9ct2kEMYE5AjckWFSTKIuMP+YXdwSchhhxIGJh5GgZdb1/7WQhRFwfJCNzTMetVVeoIEvhSagGl3+bIIsixujekIoGL,iv:rkQAoHFV+35vGvRk0Q8AqYiHw26+lJVh+QgQBcFEB6M=,tag:9b50h5+ki21HJy/I6IvW+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOVhVanR3TkV0UkJxNU15
            dzc2MXZRcXdUdnBFdDVrVUMwSmdnZGZmUWx3CjE1RVdTUVNWYmZ6anBTb0FOZk02
            OWd2WEZtT01BaDQ0c1YycllHYXhWVlUKLS0tIGx0ZHdMV083Z0RLTFBFSDJkV2xh
            bGdHL2VGbXY4bEFwV3RyMnl6N0NjSmcKvuBudXIFDEt5l4ZjCjmPhb+JaMlQkx94
            pr9oGuiZFznf50RfiFCa7jYkquAUt2KVk7iKApL0CBfQoSuTDpwgTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zdytsg2704mgqc6e76umdcgumnkx7ph70tcscs5pcauz0esp4ehsttav5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUS9sUzVHU1ovbDBCdlNR
            MHZ1bUhITEsvSE5SQlNHRndrbDg4ZjBkNG1BCjhyU0gycmRiRlhWNXJGbFN2T3Y1
            a3JRamRyN2ViamgvNCttN3hZNFI2QUkKLS0tIFZZSHpYMnRCbEVJVHZWMmUvUmQ4
            aTcwVm1XR0NpblZZamhMdlFBL0ZnNlUKwcd3++2vY9Ad5B78adeCGm+6BdUzVryj
            yeqXKueDyrQfsdr040EgJWLo8SwpJw4IonzHvxInn+yJYHUTXQQxCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-30T08:59:17Z"
    mac: ENC[AES256_GCM,data:mmDL8cyz7Daj1QspYksRpVR4eNDGoqGUHQOQjzWUW4dYei+3FbqxNcBV3wFr1mRnFH1ApXHMFbehGDiHjV35MYgjMWO0yXdvRbjWoONWQADaqocDMwNfMQZ1d25XrUb1/xTqJNO7fb6YvQ+tHXo/0VogkLWKji1uK1hRhIPMwFg=,iv:EvcHaixbERi1VaTWnQpfixmqyV6WFye+AWBpjloMR5I=,tag:SBEJ0NjdozMXcT6C3Xt3PA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
