hashedpassword: ENC[AES256_GCM,data:Jn9t4PA+uXmptzXWQec1Ve89I9DYXkT5D7VK/ufOWq2T07oJE5tS5P4An7BbIxVwT8GkWy0RW3i7O5Bsb7hpPSWmy1eBfsaXeQ==,iv:R4Txk/DDpAP8bqDqNBAMYMYtb/O8iejxTcfkauQwz8s=,tag:SAEytbvhRRxCtKilgpnbNA==,type:str]
wireless.env: ENC[AES256_GCM,data:ZM/O/wlKl9Z/f6+QJ2SEQ2S4udymxbAkdvDrh0+0,iv:zKjZ0jseCtnaSjghiiYJZQ0H//ki/ggEzo/vjDY1Xp0=,tag:DskekO93Uz4xhhfZxJXZAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySlZJNmJXVFY4MzI2MjRD
            YTVzV0cxRXdVc08vVkN6OGk3NjRYcUxXTW1JCjNSbTY0OHE2cnRUTnZxU3dBeTVs
            TmVhRkRHTEYrcjEzMmh0czNBTXBOcjAKLS0tIDZNNm03V3ZFSW54TXNqZjM3SUlJ
            S0dWOEdVdkZEMTFidHZmdWh2MmY0ejQKX3mH50rkIcChEl+dBMlWR8Yd5OZ0M/ly
            S/4dpSCBUgm2OqHn2Ch9z5v2lw6E931yUp2kfMTQy6XE8i3JxRSLMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-22T19:58:21Z"
    mac: ENC[AES256_GCM,data:fuqpR7WBGyq21PdUd5R5KNz1V+2h/5OJgl6cY8rXtqWsGTpsrh8s2qlWLgdVofjFNRYK1Xxfq3lWjrN4Q8lND56INs9zQBs0oPPAYluTsTOzjrbr+2QFFa57DNqKg0NCY6RwT8NTibAk9GmixhJ/rBt3/IvyD6a9WiqrFYRHZoc=,iv:Io3teB5nLp06WgdnTxblK2p3LOo+gnBW58YsHR2RPw8=,tag:3Dq12bYTglLhXzobxWKwEQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
