hello: ENC[AES256_GCM,data:bBJkDPMbdUWtIXcdMI8MVqxfLlo4748AlJVwX+QEZxClmlz19N/q6/QybesbeQ==,iv:1u28fCrci+HG8+8H1zgYUq5Tdv4M+T+ndU3e9PbaYQU=,tag:56Jc9uzn5RGx4jBAQ8Y9jw==,type:str]
example_key: ENC[AES256_GCM,data:7l6j7VtNDgKuY3SO,iv:AA0Ru060XrgGqTsdnK6CI4+nvAuI/qLWkbnTTMUlXA4=,tag:C6YJiWZgufziIErjZxlOUA==,type:str]
#ENC[AES256_GCM,data:/jiE0d8WKXu71GhE0D+TkA==,iv:ZPyayMdp76BGnw5J8HaAuaIXhRMfvAxKLvjElA9mKvY=,tag:B0WoPScgVFcwBiAsTm9LeQ==,type:comment]
example_array:
    - ENC[AES256_GCM,data:PhTl89siHIBqEh31fLM=,iv:ZE5EXpSt9YoapcMrgmcAWnig8Mzs7HXR86tJ4LWj0tk=,tag:EDdyt59xRCrDTdzca9b5iw==,type:str]
    - ENC[AES256_GCM,data:a1kYYXHUHMgQfAswiM4=,iv:hicHpn6wM4gd2eAblYUryIHgBvvGa8zCHYT4Kn5KlOY=,tag:L28NWs3hl6/zaITGEJC4HQ==,type:str]
example_number: ENC[AES256_GCM,data:3dO5NQxahoMLwg==,iv:Sm4P54FKDPiLAiMdQNLKHZg3W5ZEizDHbNqI1Ksm4cg=,tag:accfWWckBMBn5/d2aKAnAg==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:LYB09w==,iv:0RlvaTlR13lVbrkC+KE50hGd5xhbCm5rKsRa4uyDDxQ=,tag:DJVnixE2XNU0zdwoJFIiig==,type:bool]
    - ENC[AES256_GCM,data:Luj08l0=,iv:AuaY7Wl1udGmQIMykXmzfneHq7Gg8xiryjPs9LAs17s=,tag:OrXsFB3PJl4vZ5H4n1YCIw==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySlZJNmJXVFY4MzI2MjRD
            YTVzV0cxRXdVc08vVkN6OGk3NjRYcUxXTW1JCjNSbTY0OHE2cnRUTnZxU3dBeTVs
            TmVhRkRHTEYrcjEzMmh0czNBTXBOcjAKLS0tIDZNNm03V3ZFSW54TXNqZjM3SUlJ
            S0dWOEdVdkZEMTFidHZmdWh2MmY0ejQKX3mH50rkIcChEl+dBMlWR8Yd5OZ0M/ly
            S/4dpSCBUgm2OqHn2Ch9z5v2lw6E931yUp2kfMTQy6XE8i3JxRSLMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T14:30:58Z"
    mac: ENC[AES256_GCM,data:WxjCQXlNu2XNfnkJPOW8bBKgB12pN3Znv/SQYjpi917aR+AeH4Dx558AIKKb6VotUM2sks3r5DF/XuRwjsuDjQ6zFRxsjjaVizejwpLCitF70eSYlQp14wt8NINVI285uni9Y2okst4xSdQEj+DOmweas60WAIQ4tqPTLmz8cpY=,iv:HkNvXwnVR+AxkyIe23DUkp3/1mQAkuZWzGLCjzlsWjc=,tag:j9hMVjLx2UpaJyx9D53Vrg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
