hashedpassword: ENC[AES256_GCM,data:ALs0pJjN6aLn1LsQMqcnDe1ISb4Z3cGrkb4TVC8AxZklHkA/l20NwxFiTX777CEhiKUNC6vVP5EDbZji96sPZArS5+BvB+yH0w==,iv:hD9HcEZUvwWZr2P4BWCiSG8C8pUC9Rtl5YMjsNfg34k=,tag:/mSDep9kHPS85STgV2LwGQ==,type:str]
ANTHROPIC_API_KEY: ENC[AES256_GCM,data:5UuxRTliAEpL2T8kiD3KGK9WzIM0gqio+xmiFGxUqvN9991sp6xNG9ct2kEMYE5AjckWFSTKIuMP+YXdwSchhhxIGJh5GgZdb1/7WQhRFwfJCNzTMetVVeoIEvhSagGl3+bIIsixujekIoGL,iv:rkQAoHFV+35vGvRk0Q8AqYiHw26+lJVh+QgQBcFEB6M=,tag:9b50h5+ki21HJy/I6IvW+A==,type:str]
services:
    rclone:
        webdav-pass: ENC[AES256_GCM,data:3vkwoMggVZ8Ke5o/ege6OtWsP2ShcAS+pu6cjPQyo/mmCm3cWMgx+g5X4zBHK99Asq1u7eZMawETIcN0jaI04Y706PkXlNIP18qfiligxx0=,iv:wlgojgmIZmtkPU/cSOERJzmo6YzyyBVKs+Wamn0fKhQ=,tag:Mwlq2Frv6+TNRMXBvW8LXw==,type:str]
sops:
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOVhVanR3TkV0UkJxNU15
            dzc2MXZRcXdUdnBFdDVrVUMwSmdnZGZmUWx3CjE1RVdTUVNWYmZ6anBTb0FOZk02
            OWd2WEZtT01BaDQ0c1YycllHYXhWVlUKLS0tIGx0ZHdMV083Z0RLTFBFSDJkV2xh
            bGdHL2VGbXY4bEFwV3RyMnl6N0NjSmcKvuBudXIFDEt5l4ZjCjmPhb+JaMlQkx94
            pr9oGuiZFznf50RfiFCa7jYkquAUt2KVk7iKApL0CBfQoSuTDpwgTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zdytsg2704mgqc6e76umdcgumnkx7ph70tcscs5pcauz0esp4ehsttav5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUS9sUzVHU1ovbDBCdlNR
            MHZ1bUhITEsvSE5SQlNHRndrbDg4ZjBkNG1BCjhyU0gycmRiRlhWNXJGbFN2T3Y1
            a3JRamRyN2ViamgvNCttN3hZNFI2QUkKLS0tIFZZSHpYMnRCbEVJVHZWMmUvUmQ4
            aTcwVm1XR0NpblZZamhMdlFBL0ZnNlUKwcd3++2vY9Ad5B78adeCGm+6BdUzVryj
            yeqXKueDyrQfsdr040EgJWLo8SwpJw4IonzHvxInn+yJYHUTXQQxCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T22:19:23Z"
    mac: ENC[AES256_GCM,data:boV1/PHy1ZpAckA/Zo92tyvnf4aY5fKu1Obve5eeVYdP0xPOEELHpI74gbqXOYsQgb9WHtNdgIXvwcECrTGlbRbNFD88mo9773v9n9aArEo+OkMOa4G0zmfhqXhe+AOUaPTAgHIrisAzGxKyZL1TyJ3bngsrWuZig/ylzGMN0JE=,iv:tOmBiAWAU+PF6VO+E1r74nWppWaeM5W56RL2vplCuxg=,tag:vNSVSMmGY40pZU0WcYnVbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
