hashedpassword: ENC[AES256_GCM,data:Jn9t4PA+uXmptzXWQec1Ve89I9DYXkT5D7VK/ufOWq2T07oJE5tS5P4An7BbIxVwT8GkWy0RW3i7O5Bsb7hpPSWmy1eBfsaXeQ==,iv:R4Txk/DDpAP8bqDqNBAMYMYtb/O8iejxTcfkauQwz8s=,tag:SAEytbvhRRxCtKilgpnbNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xxs94a2jtv9ctes23rze0wgess0spqsapnpj8vrw46qx6kg98eeq20jfzt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySlZJNmJXVFY4MzI2MjRD
            YTVzV0cxRXdVc08vVkN6OGk3NjRYcUxXTW1JCjNSbTY0OHE2cnRUTnZxU3dBeTVs
            TmVhRkRHTEYrcjEzMmh0czNBTXBOcjAKLS0tIDZNNm03V3ZFSW54TXNqZjM3SUlJ
            S0dWOEdVdkZEMTFidHZmdWh2MmY0ejQKX3mH50rkIcChEl+dBMlWR8Yd5OZ0M/ly
            S/4dpSCBUgm2OqHn2Ch9z5v2lw6E931yUp2kfMTQy6XE8i3JxRSLMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T09:46:25Z"
    mac: ENC[AES256_GCM,data:6QnvMKmOjl9wd70t7u0pzVQkv0ms8wO0Ty9x44ouXnHKA//csgZidz6UgnXReyThqclLfpen2uMiUdGxK2srNykxmCMm8CJ1DbQ5xPdWGDgGtF6ErRl0o9EyLP8mQFbLzirYMaNSRxnpPTZ9nKe22kLHWE0nTx4SDBEi1OIXW9c=,iv:yWKxAMzS+Zk22G0nUoA29xlLllfcWKXyDSu6aLask/Q=,tag:hemDrs7r5oNodN5rJ4EMJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
